// Writes crates/shared/src/swift_string/tables.rs: the scalars whose character properties in
// Swift's runtime differ from Unicode's, which Rust's standard library follows. Run it on a Mac
// after a macOS or Xcode update, and commit the result if it changed:
//
//     swiftc -O tools/swift-character-tables.swift -o /tmp/swift-character-tables
//     /tmp/swift-character-tables > crates/shared/src/swift_string/tables.rs
//
// Everything else the port relies on (white space, punctuation, symbols, case, emoji, grapheme
// breaks) matched Swift's runtime scalar by scalar when this was written.
import Foundation

/// Consecutive scalars that pass `include`, as closed ranges.
func ranges(_ include: (Unicode.Scalar) -> Bool) -> [(UInt32, UInt32)] {
    var found: [(UInt32, UInt32)] = []
    for value in UInt32(0)...0x10FFFF {
        guard let scalar = Unicode.Scalar(value), include(scalar) else { continue }
        if let last = found.last, last.1 + 1 == value {
            found[found.count - 1] = (last.0, value)
        } else {
            found.append((value, value))
        }
    }
    return found
}

func table(_ name: String, _ doc: [String], _ found: [(UInt32, UInt32)]) -> String {
    let rows = found.map { String(format: "    ('\\u{%X}', '\\u{%X}'),", $0.0, $0.1) }
    return (doc.map { "/// \($0)" } + ["pub(super) const \(name): &[(char, char)] = &["] + rows + ["];"])
        .joined(separator: "\n")
}

let numbers = ranges { scalar in
    guard scalar.properties.numericType != nil else { return false }
    switch scalar.properties.generalCategory {
    case .decimalNumber, .letterNumber, .otherNumber: return false
    default: return true
    }
}
let letters = ranges { $0.properties.isAlphabetic && $0.properties.generalCategory == .privateUse }

print("""
// Generated by tools/swift-character-tables.swift; do not edit.

\(table("NUMBERS_OUTSIDE_NUMBER_CATEGORIES", [
    "Scalars with a numeric type that are not in a number category: Han numerals such as 一, 万",
    "and 億. Swift's `Character.isNumber` counts them; Rust's `char::is_numeric` does not.",
], numbers))

\(table("PRIVATE_USE_LETTERS", [
    "Private-use scalars that Swift's `Character.isLetter` counts as letters, as Apple's",
    "platforms assign them; Unicode leaves every private-use scalar without properties.",
], letters))
""")
