import Foundation

/// Finished texts with placeholder tokens: `{tok}` stands for one emoji, link, address, number or
/// snippet that the app inserts later (to the model it is one opaque word), and `{mark}` for a
/// spoken "number one, number two" marker that the app replaced. `[said|written]` is a recogniser
/// slip that the writing must resolve.
extension DeepLayoutFrames {
    /// Texts with `{tok}` in the shapes the model meets: after a finished sentence, between two
    /// sentences, inside a sentence, at the start, as an object, in a row, in a list-like phrase,
    /// after a name and after a question.
    static let tokenFramesTrain: [String] = [
        // After a complete sentence, at the end of the text.
        "The new [higher|hire] starts in {city} on {weekday}. {tok}",
        "Your parcel shipped this morning. {tok}",
        "The committee approved the budget for next year. {tok}",
        "Dinner is at {time} at the corner cafe. {tok}",
        "We finished the tiling [a head|ahead] of schedule. {tok}",
        "Remember to drink plenty of water today. {tok}",
        "The server migration completed without any errors. {tok}",
        "Congratulations on the promotion, {name}. {tok}",
        "Practice moves to the back field on {weekday}. {tok}",
        "The plumber will arrive at {time}. {tok}",
        "Our flight from {city} was delayed by an [our|hour]. {tok}",
        "I finally [past|passed] my driving test. {tok}",
        "The kids were fast asleep [buy|by] eight. {tok}",
        "{name} is on the train and will be late. {tok}",
        "Thank you for your patience while we fixed the outage. {tok}",
        "The [hole|whole] team will handle the booking. {tok}",
        "The bakery ran out of sourdough by noon. {tok}",
        "The ferry to {city} [sales|sails] at {time}. {tok}",
        "The [brakes|breaks] on my bike finally work. {tok}",
        "Mum's hip operation went well. {tok}",
        "The [rein|rain] stopped just before the parade. {tok}",
        "I [hand it|handed] in the final essay at lunchtime. {tok}",
        "We saved you a [peace|piece] of cake. {tok}",
        // Between two sentences.
        "That was a great talk, {name}. {tok} Let's get coffee on {weekday}.",
        "The car is finally fixed. {tok} I can pick you up at {time}.",
        "Sorry I missed [you're|your] call. {tok} I will ring you back after lunch.",
        "We won the semi-final! {tok} The final is on {weekday}.",
        "The report is ready. {tok} Please read it before {event}.",
        "Your table is booked for {time} on {weekday}. {tok} Please arrive ten minutes early.",
        "Welcome to the team, {name}. {tok} Your desk is next to the window.",
        "I passed the exam. {tok} Mum is taking us out to [diner|dinner].",
        "The roof is leaking again. {tok} I called the builder this morning.",
        "Nice work on the release. {tok} The customers are [all ready|already] happy.",
        "I lost my keys again. {tok} The locksmith is coming at {time}.",
        "Thank you for the [flours|flowers]. {tok} They brightened up the whole house.",
        "Happy [knew|new] year everyone. {tok} May it be a healthy one.",
        "The match was called off. {tok} We will [reply|replay] it in {month}.",
        "I love this photo. {tok} Can you send me the rest?",
        "Dinner was lovely and the [stake|steak] was perfect. {tok} We will go back soon.",
        "Please [here|hear] me out. {tok} I think the plan can still work.",
        "Thanks for organising {event}. {tok} Everyone said it ran beautifully.",
        "I found a cheap flight to {city}. {tok} It leaves on {weekday} morning.",
        "The exam results are out. {tok} I got a B in chemistry.",
        "The garage door is stuck. {tok} I am [weighting|waiting] for the repair man.",
        "Our quarterly numbers look healthy. {tok} I will share the details after {event}.",
        // In the middle of a sentence, after a noun or a name, without commas.
        "The garden {tok} needs watering twice a [weak|week].",
        "{name} {tok} is bringing the folding chairs on {weekday}.",
        "Leave the keys {tok} [hear|here] on the shelf.",
        "The new printer {tok} keeps jamming on thick paper.",
        "My [ant|aunt] {tok} is visiting from {city} next month.",
        "The team {tok} shipped the feature a day early.",
        "[There|Their] neighbours {tok} are hosting the street party this year.",
        "The soup {tok} needs a little more salt.",
        "Please keep the noise down {tok} while the baby sleeps.",
        "The concert {tok} starts at {time} sharp.",
        "We [paint it|painted] the fence {tok} over the weekend.",
        "She {tok} scored twice in the second half.",
        "The museum {tok} is free for students on {weekday}.",
        "I am so proud of the choir {tok} after that performance.",
        "My physio {tok} says the knee will be fine by {month}.",
        "The lasagne {tok} needs another ten minutes in the oven.",
        "The front door {tok} is sticking again.",
        "The whole family {tok} is coming to the wedding in {month}.",
        "The library {tok} closes early on Fridays.",
        "We [herd|heard] the news {tok} from the neighbours.",
        // At the start of the text.
        "{tok} The bus was late again this morning.",
        "{tok} I can't believe it is already {month}.",
        "{tok} Dad says the barbecue is ready.",
        "{tok} Please bring a jumper because it will get cold.",
        "{tok} The dentist has moved my appointment to {weekday}.",
        "{tok} {name} just called about the tickets.",
        "{tok} The kettle is broken so use the pot.",
        "{tok} We are out of coffee.",
        "{tok} The school trip is on after all.",
        "{tok} The [sight|site] manager called about the delivery.",
        "{tok} Is [their|there] a spare seat in the back?",
        // A link or an address used as an object.
        "Email the updated timesheet to {tok} before lunch.",
        "Register your team at {tok} before the deadline.",
        "Upload the receipts to {tok} by the end of {month}.",
        "Book your slot at {tok} and bring a photo ID.",
        "Follow the setup guide at {tok} before you install anything.",
        "You can reach the front desk at {tok} until six.",
        "Text me on {tok} when you get [too|to] the station.",
        "The survey is open at {tok} until {weekday}.",
        "Add your comments to the thread at {tok} so nobody misses them.",
        "Open the shared folder at {tok} and add [you're|your] notes.",
        "Forward the confirmation to {tok} and keep a copy.",
        "Sign up for the swim lessons at {tok} this week.",
        "Please ring {tok} if the gate is locked.",
        "The recipe is at {tok} and it only takes twenty minutes.",
        "[Right|Write] to {tok} if the invoice has any errors.",
        "Download the map from {tok} before you leave.",
        "Order the [flours|flowers] from {tok} at least a week ahead.",
        "Send your notes from {event} to {tok} before Friday.",
        "Call the garage on {tok} to book the service.",
        "Our new address is {tok} so please update your records.",
        "Join the class at {tok} ten minutes early [too|to] test your audio.",
        "You will find the full schedule at {tok} under the events tab.",
        "Message the landlord on {tok} if the boiler stops again.",
        "The spare key is in the box and the code is {tok}.",
        "Post the photos from the trip at {tok} for the others.",
        "Please fill in the health form at {tok} before your first visit.",
        "Reserve a court at {tok} for Saturday morning.",
        // Two or three tokens in a row.
        "Happy anniversary you two! {tok} {tok} {tok} Have a lovely dinner tonight.",
        "Good luck tomorrow! {tok} {tok} You will be brilliant.",
        "We did it! {tok} {tok} {tok} Drinks are on me.",
        "Get well soon, {name}. {tok} {tok} We are all thinking of you.",
        "Merry Christmas everyone! {tok} {tok} See you all in the new year.",
        "Congratulations to you both! {tok} {tok} {tok} Wishing you a wonderful life together.",
        "Thanks so much {tok} {tok} for [lucking|looking] after the dog.",
        "Safe travels! {tok} {tok} Message me when you land in {city}.",
        "Welcome home, {name}! {tok} {tok} The kettle is on.",
        "Sorry to hear that. {tok} {tok} Call me if you need anything.",
        "Bravo! {tok} {tok} That was the best set of the night.",
        // Inside a longer sentence with a list-like phrase.
        "We need tape, scissors and [clue|glue] {tok} for the craft table.",
        "Pack a torch, a blanket and some snacks {tok} for the [camp site|campsite].",
        "The call covers budgets, hiring and the roadmap {tok} for next quarter.",
        "I bought apples, [pairs|pears] and plums {tok} at the market.",
        "The team includes {name}, Tomas and Greta {tok} from the design group.",
        "We need a drill, a level and some wall plugs {tok} for the shelves.",
        "The fees cover the venue, the catering and the band {tok} for the evening.",
        "You will need a laptop, a charger and a headset {tok} for the workshop.",
        "The menu has soup, salad and grilled fish {tok} for the main course.",
        // After a name.
        "Please say hello to Tomas {tok} when you see him.",
        "Tell Greta {tok} that the keys are under the mat.",
        "Dmitri {tok} is leading the session this time.",
        "Give {name} {tok} a call about the carpool.",
        "Thanks again {name} {tok} for the lift home.",
        "Olivia {tok} will collect the trophies after the game.",
        // After a question.
        "Are you coming to {event}? {tok}",
        "Can you pick up the kids at {time}? {tok}",
        "Did the courier leave the parcel with the neighbours? {tok}",
        "[Wear|Where] should we meet on {weekday}? {tok}",
        "Is the printer working again? {tok} I need the forms by noon.",
        "Who is bringing the speakers? {tok}",
        "Do you have time for a quick call at {time}? {tok}",
        "How was the interview? {tok} Tell me everything.",
        "Has anyone seen my umbrella? {tok}",
        "Shall we order pizza [to night|tonight]? {tok}",
        "Would [you're|your] team like to join us? {tok}",
        "Did the [mail|male] arrive before lunch? {tok}",
    ]

    static let tokenFramesTest: [String] = [
        "I am baking a lemon cake for the fundraiser. {tok}",
        "Great game tonight, {name}. {tok} The whole stand was on its feet.",
        "The vet called to say the results are back. {tok}",
        "Our landlord {tok} promised to fix the lift by Friday.",
        "{tok} The lecture has moved to the science block.",
        "Please submit the expense claim to {tok} before the month ends.",
        "Follow the trail markers to the lookout {tok} and stop for photos.",
        "The coffee is on the counter. {tok} {tok} Help yourselves.",
        "Did the cleaners lock up last night? {tok}",
        "We need cables, adapters and a spare monitor {tok} for the demo room.",
        "Sending hugs to you and the family, {name}. {tok} {tok} {tok}",
        "We can [sea|see] the harbour from the balcony. {tok}",
        "[Your|You're] welcome to join us for the tasting {tok} on Saturday.",
        "I am heading to the pharmacy. {tok} Do you want anything?",
        "Check the noticeboard at {tok} for the latest timetable changes.",
        "The orchestra {tok} begins its autumn tour next week.",
        "I will drop the kids at school {tok} and then head to the gym.",
        "Tell Yusuf {tok} the delivery window is between nine and noon.",
        "The yoga class is full. {tok} I put you on the waiting list.",
        "They [where|were] very kind to us at the clinic. {tok}",
        "Join the neighbourhood group at {tok} to hear about the clean-up day.",
        "The roof inspection passed first time. {tok}",
        "What time is [hour|our] flight? {tok}",
        "The [plain|plane] landed twenty minutes early. {tok}",
        "The bookshop {tok} sells maps of the old town.",
        "I am so glad you made it home safely. {tok}",
        "I can't [weight|wait] to see the new flat. {tok}",
        "Our new flat {tok} has a view of the canal.",
        "Is the wifi password on the fridge? {tok}",
        "Please [meat|meet] us at the main entrance {tok} at {time}.",
        "I have a dentist appointment on {weekday}. {tok} Can we move the call?",
        "Send the final drawings to {tok} so the builders can start.",
        "Our team is [threw|through] to the next round. {tok}",
        "Hana {tok} has offered to run the raffle.",
    ]

    /// One-paragraph texts in which the speaker said "number one, ... number two, ..." and the app
    /// turned each spoken marker into `{mark}`: an intro, then whole-sentence items, and sometimes a
    /// closing sentence.
    static let markerFramesTrain: [String] = [
        "Here is my feedback on the onboarding flow. {mark} The welcome screen has too much text. {mark} The progress bar never updates. {mark} The final button is hard to see.",
        "I reviewed the draft policy over lunch. {mark} The opening paragraph is far too long. {mark} The refund section contradicts the terms page. {mark} The glossary needs a few more entries. That's all from me.",
        "There are a few problems with the flat. {mark} The shower drains very slowly. {mark} The kitchen light flickers at night.",
        "The plan for the school concert has four parts. {mark} We book the hall on Monday. {mark} We print the programmes by Wednesday. {mark} We rehearse the final song on Thursday. {mark} We open the doors at six.",
        "My requirements for the new dashboard are simple. {mark} It must load in under two seconds. {mark} It must work on a phone. {mark} It must let me export a report.",
        "To get the garden ready for spring, I have a few jobs. {mark} I will prune the roses. {mark} I will turn over the vegetable beds. {mark} I will repair the gate latch. That should keep me busy.",
        "I have some notes on yesterday's interview. {mark} The candidate explained her last project very clearly. {mark} She [new|knew] the programming language well. {mark} Her questions about the team were thoughtful. I would hire her.",
        "Here is what went wrong with the delivery. {mark} The courier went to the wrong address. {mark} The driver never rang the bell. {mark} The tracking page showed the wrong status.",
        "I have three reasons for supporting the new rota. {mark} It gives everyone a fair share of weekends. {mark} It is easier to plan around. {mark} It cuts down on last-minute swaps.",
        "To reset your password, follow these instructions. {mark} Open the sign-in page. {mark} Choose the forgot password link. {mark} Enter the email on your account. {mark} Check your inbox for the code.",
        "Here is a quick update on the allotment. {mark} The shed roof is now finished. {mark} The water butt is full. Everything else can wait until spring.",
        "I have some feedback for the catering team. {mark} The vegetarian option ran out early. {mark} The coffee was cold by nine. {mark} The [hole|whole] desk team were friendly and quick. Thanks for all your effort.",
        "Here is what I liked about the apartment. {mark} The living room gets plenty of light. {mark} The balcony looks over a park. {mark} The building has secure bike storage.",
        "The team raised a few concerns about the launch. {mark} The load tests have not been run. {mark} The help pages are still in draft. {mark} The rollback plan is unclear. {mark} Nobody has signed off the pricing.",
        "Before the house inspection, I want to check a few things. {mark} The smoke alarms need new batteries. {mark} The fence panel by the shed is loose.",
        "The coach gave us some tips after the match. {mark} Keep your head up when you [past|pass]. {mark} Talk to each other at corners. {mark} Stay calm when we are behind. That was his advice.",
        "These are the main risks for the project. {mark} The vendor may miss the delivery date. {mark} The budget has no buffer for changes. {mark} The test lab is [to|too] small for the whole team.",
        "I have a few requests for the landlord. {mark} Please replace the broken window latch. {mark} Please repaint the hallway before we move in. {mark} Please confirm the start date in [righting|writing].",
        "I took away a few lessons from the workshop. {mark} Short meetings get more done. {mark} Written notes beat memory every time. {mark} Clear owners matter more than clear deadlines.",
        "We need to fix a few things in the app before release. {mark} The search box ignores capital letters. {mark} The settings page crashes on older phones. {mark} The logout button sits too close to the save button. That's the lot.",
        "For the bake sale I have a simple plan. {mark} I will make two trays of flapjacks. {mark} You can bring the lemonade. {mark} Someone else can run the cash box.",
        "My priorities this month are clear. {mark} I want to finish the quarterly report. {mark} I want to hire a second designer. {mark} I want to take a proper holiday.",
        "Here is what the survey told us. {mark} Most members want longer opening hours. {mark} Many asked for a quieter room. {mark} A few would like a cafe on site.",
        "The doctor gave me some advice. {mark} Walk for thirty minutes every day. {mark} Drink more water. {mark} Go to bed before eleven. {mark} Come back in six weeks.",
        "I made a few observations during the site visit. {mark} The foundations look solid. {mark} The drainage channel is blocked with leaves. {mark} The access road is narrow for large lorries.",
        "Setting up the projector for the lecture takes three steps. {mark} Connect the power cable first. {mark} Plug in the video lead. {mark} Select the correct input on the remote.",
        "I want to say two things about the merger. {mark} The staff deserve an early briefing. {mark} The customers deserve a clear message.",
        "These are my notes from the parents evening. {mark} Her reading has improved a lot this term. {mark} She needs more [practise|practice] with fractions. {mark} She has made good friends in the class.",
        "This is what we need from the contractor. {mark} We need a fixed quote for the [hole|whole] job. {mark} We need a start date we can rely on. {mark} We need a named person to call.",
        "I have some ideas for the club's summer event. {mark} We could hold a quiz in the marquee. {mark} We could invite the local band. {mark} We could raffle a weekend away. {mark} We could ask the school to lend us tables. Let me know what you think.",
        "The audit raised several issues. {mark} Expense receipts were missing for two trips. {mark} Two contracts had no signature. {mark} Staff leaving the company kept [there|their] access for weeks.",
        "There are a few things I love about this neighbourhood. {mark} The baker opens at six. {mark} The park is five minutes away. {mark} The bus to the city runs every ten minutes.",
        "I have a few reminders for the trip. {mark} Charge the camera [to night|tonight]. {mark} Leave the spare key with the neighbour. {mark} Check that the tickets are in the bag.",
        "I am writing to summarise my complaint. {mark} The heating failed on Tuesday. {mark} The engineer did not arrive on the day promised. {mark} We were not told about the delay. That is why I am writing.",
        "I have a few wishes for the weekend. {mark} I want to sleep in. {mark} I want to [by|buy] fresh flowers. {mark} I want a long walk by the river.",
        "Our hiring plan for the year comes down to two points. {mark} We add one engineer in the spring. {mark} We add a support lead before the summer rush.",
        "Here is how I would improve the invoice process. {mark} Suppliers should upload invoices to one portal. {mark} Approvals should happen within two working days. {mark} Payments should go out every Friday. {mark} Disputes should have a single owner.",
        "These are the things the tenants asked about. {mark} The car park needs resurfacing. {mark} The lift has been broken for a month. {mark} The bins are too close to the windows.",
    ]

    static let markerFramesTest: [String] = [
        "Some notes after the fire drill. {mark} The alarm was clear in every room. {mark} The stairwell was crowded at the start. {mark} Everyone was [out side|outside] in four minutes. Good result overall.",
        "I have a few wishes for the new library. {mark} The opening hours should stay long. {mark} There should be more desks near the windows. {mark} The shelves need more books in other languages.",
        "Here is what to do if the freezer stops working. {mark} Check that the plug is in the socket. {mark} Look at the fuse box. {mark} Keep the door closed. {mark} Call the repair line.",
        "Here is how the trial went. {mark} The first group finished in twenty minutes. {mark} The second group got stuck on the payment page. {mark} Nobody [new|knew] where the help button was.",
        "I have a case for moving the office. {mark} The rent is lower across the river. {mark} Most of the team lives nearby. {mark} There is parking for visitors.",
        "The vet explained the recovery plan. {mark} Keep the cone on for ten days. {mark} Give the tablets with food. {mark} Bring him back next week for a check. That is everything.",
        "There are a few things I would change about the festival. {mark} The queues for the food stalls were too long. {mark} The toilets needed more cleaning. {mark} The stage should face away from the houses. {mark} The signs were hard to read in the dark.",
        "I have some thoughts on the coding exercise. {mark} The brief was short but clear. {mark} The time limit felt fair. {mark} The sample data had a few odd rows.",
        "Our goals for the choir this year are modest. {mark} We will learn six new pieces. {mark} We will perform at the hospital in {month}. {mark} We will welcome at least ten new singers. Fingers crossed.",
        "A few things surprised me about the job. {mark} The team shares lunch every Friday. {mark} The manager answers messages within minutes. {mark} The office has a quiet room for naps.",
        "The bus company promised three changes to the timetable. {mark} Evening buses will run until midnight. {mark} The morning service will start earlier. {mark} Sunday buses will stop at the hospital.",
        "Here is my case for the later start. {mark} Students sleep better and arrive alert. {mark} Fewer children are late for first period. {mark} Parents can drop off after the commute peak.",
    ]
}
