import Foundation

/// Email bodies for Deep's layout examples: finished text with no greeting and no sign-off, one
/// paragraph each. `[said|written]` marks a recogniser slip: the generator speaks the left side and
/// expects the right side. Words such as "thanks", "sorry", "actually" and "no" are used in their
/// ordinary sense and must stay as said.
extension DeepLayoutFrames {
    static let bodiesTrain: [String] = [
        // Project updates
        "The mobile build passed every check this morning, and the store review starts tomorrow.",
        "We finished the database upgrade ahead of schedule. Nothing needs to change on your side.",
        "The kitchen renovation is about two weeks behind because the cabinets arrived damaged. The fitters are back on {weekday}.",
        "Progress on {doc} has been steady. I expect a first draft before the weekend.",
        "The roof repair is complete, and the scaffolding comes down on {weekday}.",
        "[Are|Our] testing showed a memory leak in the upload service. A fix is already in review.",
        "The sprint review went well. The team demoed three features, and the client asked for one small change.",
        "The electrics in the garage passed inspection, so the plasterers can begin next week.",
        "The translation of the help pages is half done. I will send the rest once the glossary is approved.",
        // Requests
        "Could you send me the latest floor plan before {weekday}? The builder needs it to finalise the quote.",
        "I would appreciate it if you could review {doc} and tell me whether the totals look right.",
        "Please [right|write] back with the dates that suit you best. I will book the rooms as soon as I hear.",
        "Would you mind covering my shift on {weekday}? My sister is visiting from out of town.",
        "Can someone from your team join a short call about the export error? Any afternoon this week works for me.",
        "I need access to the shared drive for the marketing folder. My manager can approve it if required.",
        "Please hand the completed form to the front office by noon on {weekday}.",
        // Thanks
        "Thank you all for coming to {event} and for staying late to help pack up. It meant a great deal.",
        "Thanks so much for lending us your projector. The talk went well, and nobody noticed the flickering.",
        "I wanted to thank you for the warm welcome during my first week. Everyone has been very kind.",
        "Many thanks to the volunteers who [sort|sorted] the donations on Saturday. We filled two full vans.",
        "Thanks for the lift to the airport on {weekday}. I owe you a coffee.",
        // Apologies
        "I'm sorry for missing {event} yesterday. My train was cancelled and my phone had no battery.",
        "Apologies for getting the dates wrong in my last message. The right ones are on the attached calendar.",
        "Sorry about the noise from the building work last week. It should be finished by Friday.",
        "We apologise for the delay in replying. Your request was sent to the wrong team by mistake.",
        "I am sorry that the parcel arrived too late for your event.",
        // Scheduling
        "Can we move the catch-up to {weekday} at {time}? I have a clash in the morning.",
        "The coach will pick the team up at {time} from the car park behind the school.",
        "I've booked a table for six at the restaurant near the station on {weekday} evening. Let me know if numbers change.",
        "The plumber can come on {weekday} between nine and twelve. Will someone be home?",
        "Our next committee meeting is on {weekday} in the main hall. Please bring your reports.",
        "Let's [meat|meet] at the front gate at {time}, and we can walk in together.",
        // Feedback
        "The presentation was clear and well paced. I would add one slide on costs, though.",
        "Your code is easy to follow. I left two small comments about naming in the review.",
        "I [red|read] the draft on the train this morning. The second section needs more evidence.",
        "The new landing page loads fast, but the contact form is hard to find on a phone.",
        "Overall the essay is strong, but the conclusion repeats the introduction too closely.",
        "The team responded well to the new rota. A few people asked for longer breaks.",
        // Complaints
        "The heating in our flat has been off since Monday. Please send an engineer as soon as possible.",
        "I ordered a blue desk lamp, but a white one arrived. I would like an exchange.",
        "The bus was forty minutes late this morning, and nobody at the stop could tell us why.",
        "We were charged twice for the same booking. Please refund the extra payment to my card.",
        "The delivery driver left the parcel in the rain, and the box was soaked through.",
        // Enquiries
        "Do you have any rooms available in {city} for the weekend of the twelfth? We would need two.",
        "I'm writing to ask whether your gym offers a student rate. I would like to join in January.",
        "Could you tell me how long the warranty lasts on the standing desk? I can't find it on the website.",
        "Is the course still open for enrolment? My daughter would like to start after the holidays.",
        "I'd like to know whether the venue has step-free access. One of our guests uses a wheelchair.",
        // Reminders
        "A quick reminder that timesheets are due by five on {weekday}.",
        "Don't forget to bring your running shoes tomorrow. The track opens at {time}.",
        "This is a reminder that your library books are due back on the tenth.",
        "Just a reminder that {event} starts at {time} sharp, so please arrive a little early.",
        "Your dentist appointment is tomorrow morning. Please arrive ten minutes early to fill in the forms.",
        // Confirmations
        "I can confirm that your order shipped this afternoon. You should have it within three working days.",
        "This confirms your booking for {event} in {month}. A receipt is attached.",
        "Your application has been received, and we will reply within two weeks.",
        "We're all set for {weekday}. The caterers are booked and the room is ready.",
        "I've added you to the list for the field trip. Please return the permission slip by Friday.",
        // Introductions
        "{name} has just joined our design team and will be working with you on the new app.",
        "I'm the new treasurer of the rowing club, and I wanted to introduce myself. I look forward to working with you.",
        "A colleague, {name}, suggested I contact you about the warehouse project. I'd be glad to tell you more.",
        "I'm writing to introduce our new supplier in {city}. Their prices are lower, and they deliver twice a week.",
        // Invoices and payments
        "The invoice for the consulting work completed in {month} is attached. Payment is due within thirty days.",
        "Your payment was received on Monday, and your account is now up to date.",
        "The amount on the statement includes the late fee. We can waive it if you pay this week.",
        "I haven't yet received payment for the last two deliveries. Could you check with your accounts team?",
        "Our bank details have changed, so please use the new ones on the attached form. The old account closes at the end of {month}.",
        // Hiring
        "We would like to invite you to a second interview on {weekday}. It will take about an hour.",
        "Thank you for applying for the support role. Unfortunately we have chosen another candidate, but we will keep your details on file.",
        "The team loved your portfolio. We'd like to offer you the designer position, starting on the first of {month}.",
        "Could you send two references before the interview? Current managers are fine.",
        "The advert for the junior analyst closes next Friday. We have had thirty applications so far.",
        // School and club notices
        "The school trip to the science museum has moved to {weekday} because of the weather forecast.",
        "Choir practice is cancelled this week because the hall is being painted. We resume the following Thursday.",
        "Parents are invited to the end of term concert in the gym. The hall opens at {time}.",
        "The football club is looking for a new secretary. If you are interested, please speak to the coach.",
        "The uniform sale is in the school office on Tuesday after class. Second-hand jumpers are five dollars.",
        "Our annual bake sale raised more than eight hundred dollars for new library books. Thank you to everyone who baked.",
        // Casual
        "Are you still up for climbing on the weekend? The forecast looks good for Saturday.",
        "Sorry, I can't make dinner tonight. Something came up at work. Rain check?",
        "No, I haven't seen your keys. Have you checked the coat you wore on Sunday?",
        "Actually, let's skip the museum and go to the beach. The kids will love it.",
        // Recogniser slips
        "The documents are over [their|there] on the shelf in the back office.",
        "We [should of|should have] booked the larger room for the workshop.",
        "The council [have|has] approved the budget for next year, and the work starts in spring.",
        "The [break|brake] pads on the minibus need replacing before the trip.",
        "[Its|It's] been a busy month for the support team, and we are all glad it's over.",
        "I am not sure [weather|whether] the courier has our new address.",
        "We don't want to [loose|lose] the booking, so please pay the deposit today.",
        "[Your|You're] welcome to bring a guest to the dinner on {weekday}.",
        "The report [include|includes] three charts and a short summary of the survey results.",
        "[Their|They're] planning to [meat|meet] the supplier on {weekday} to sort out the order.",
        "The two engineers [is|are] available on {weekday} afternoon.",
        "Please [sea|see] the attached map for directions to the hall.",
        "We [where|were] told the road would be closed for a week.",
        "Could you [bare|bear] with us while we move offices? The phones should be back by Tuesday.",
        "Do you know [were|where] the spare keys are kept?",
        "I would like to [by|buy] two more tickets for the raffle at the school fair.",
        "The new bins [was|were] delivered on Tuesday, and the old ones go back next week.",
        "Sorry, the printer is out of order, so I have not been able to print your forms.",
        "No, the meeting has not moved. [Its|It's] still at {time} in the training room.",
        "Thanks for the feedback. I [could of|could have] explained the pricing more clearly.",
    ]

    static let bodiesTest: [String] = [
        "The quarterly review is now in the smaller meeting room on the second floor.",
        "I have attached the site map and the electrician's quote. The total is still under budget.",
        "Do you know if the lab is free on {weekday}? We need it for a short experiment, and it should only take an hour.",
        "I mixed up the tables on the seating chart. I have fixed it and sent the new version.",
        "Thanks for looking after the cat while we were away. She seems happier than ever.",
        "Two of the volunteers [was|were] stuck in traffic and arrived late.",
        "No, the library isn't open on Sundays. It closes at four on Saturdays.",
        "Our flight to {city} lands at {time}, so dinner may have to wait.",
        "Turn [write|right] at the post office, and the hall is next to the bakery.",
        "Actually, the quote does not cover delivery. Could you confirm the extra charge?",
        "I'm writing to enquire about renting the community hall for a birthday party in {month}.",
        "Your money has been returned to the card you used. Your bank may take a few days to show it.",
        "{name} has offered to drive the juniors to the tournament, so we only need one more car.",
        "The smoke alarm in the hallway keeps beeping. Could the landlord send someone to replace the battery?",
        "Congratulations on your promotion to shift supervisor. The new pay band begins in {month}.",
        "The [principle|principal] would like to thank parents for their help with sports day.",
        "A reminder that the recycling truck comes early on Wednesday, so put the bins out tonight.",
        "I'd like to introduce you to {name}, our new contractor for the garden project. Please share the site plan.",
        "Our team finished the audit a day early. The auditors [past|passed] every safety check.",
        "Can we swap the workshop and the lunch? The speaker has to leave at {time}.",
        "I'm sorry to say the concert is sold out, but we can add you to the waiting list.",
        "The paint you chose is back in stock. I can have it delivered to the house on {weekday}.",
        "The cleaning rota for the clubhouse changes next month. Please check the noticeboard for your name.",
        "We [herd|heard] back from the council, and the permit for the street party is approved.",
        "Thank you for the detailed notes from the workshop. They made the follow-up so much easier.",
        "The allotment gates will be locked from seven this evening. Please collect your tools before then.",
        "The marathon route is changing this year, so the water stations will be in new places.",
        "Would it be possible to borrow a ladder for the weekend? I only need it to clear the gutters.",
        "The bakery order for the fundraiser is confirmed, and they will deliver the trays by eight.",
        "I'll [weight|wait] for your reply before I order the extra chairs for the hall.",
    ]
}
