import Foundation

/// Series that stay inside a sentence (not lists) and colon sentences that introduce one thing.
extension DeepLayoutFrames {
    /// Sentences with one `{series:key}` (2 to 4 values) or `{pair:key}` (exactly two). The series
    /// sits inside a sentence that keeps going, or states a fact, preference, past event or
    /// description. Frames that start with a slot only use keys whose values are proper nouns.
    static let seriesFramesTrain: [String] = [
        "We visited {series:places} last summer and loved all of them.",
        "My sister has lived in {series:places} since she left school.",
        "The choir toured {series:places} before the concert season ended.",
        "Our cousins are flying out to {series:places} in the spring.",
        "{series:places} were all hit by the storm, but the power came back within a day.",
        "I have never been to {pair:places}, though everyone says I should go.",
        "{series:people} are on the committee this year.",
        "The prize went to {pair:people} after a long discussion.",
        "I shared a flat with {series:people} during my first year at university.",
        "{pair:people} were late because the bus broke down.",
        "The wedding was organised by {series:people} over a couple of months.",
        "Our neighbours {series:people} came round with a cake on Sunday.",
        "The kids prefer {pair:snacks} over anything else.",
        "At the match we shared {series:snacks} and watched the second half in the rain.",
        "My grandmother always keeps {series:snacks} in the tin by the door.",
        "The vending machine downstairs sells {series:snacks} and is usually empty by lunch.",
        "I packed {series:gear} for the weekend trek.",
        "She checked {series:gear} twice before the climb.",
        "The guide had already loaded {series:gear} onto the truck.",
        "We left {series:gear} at the campsite and went back for them on Sunday.",
        "My son takes part in {series:sports} at school and is exhausted by Friday.",
        "The leisure centre offers coaching in {series:sports} on weekday evenings.",
        "The two most popular sports at our school are {pair:sports}, by a wide margin.",
        "She gave up {series:sports} when the twins were born.",
        "Our daughter studies {series:subjects} and hopes to go to university next year.",
        "The teacher marked {series:subjects} papers all weekend.",
        "He dropped {pair:subjects} after the first term and never looked back.",
        "The school will teach {series:subjects} in the new wing next year.",
        "We spotted {series:animals} on the coast path before breakfast.",
        "The farm keeps {series:farmanimals} and sells eggs at the gate.",
        "The vet came out on Tuesday to check {pair:farmanimals} for the farmer.",
        "The children at the workshop drew {pair:animals} and then painted them.",
        "The reserve is home to {series:animals} as well as several rare orchids.",
        "The walls in the hallway are painted {pair:colours} with white trim.",
        "She knitted the scarf in {series:colours} for her brother.",
        "The flag uses {series:colours} on a plain background.",
        "We chose {series:colours} for the cushions, and the sofa stayed grey.",
        "My aunt plays {series:instruments} and teaches them all.",
        "The school lent {pair:instruments} to the new students.",
        "I learned {series:instruments} as a child and still play them at parties.",
        "The concert featured {series:instruments} and ended with a standing ovation.",
        "{series:cuisines} restaurants line the high street near the station.",
        "We ate {series:cuisines} food on the trip and never got tired of it.",
        "The festival had stalls serving {pair:cuisines} dishes all weekend.",
        "{series:teams} all reached the semi-finals this year.",
        "Our school plays {series:teams} in the autumn league.",
        "The cup draw put {pair:teams} in the same group.",
        "My neighbour speaks {series:languages} and helps out at the clinic.",
        "The course is taught in {pair:languages} at the moment.",
        "{series:languages} are all offered as evening classes at the college.",
        "The carpenter brought {series:tools} and got to work straight away.",
        "I borrowed {series:tools} from my dad and forgot to return them.",
        "The shed holds {series:tools} and very little else.",
        "He laid out {pair:tools} before the job started.",
        "We grow {series:crops} on the allotment behind the school.",
        "The market stall sells {series:crops} that were picked that morning.",
        "The frost killed {pair:crops} in the north field last week.",
        "The flat came with {series:furniture} when we moved in.",
        "They sold {series:furniture} before moving abroad.",
        "The showroom has {pair:furniture} on sale until the end of the month.",
        "The outage affected {series:services} for about forty minutes.",
        "Yesterday the team migrated {series:services} to the new cluster without any downtime.",
        "The dashboard shows alerts for {pair:services} at the moment.",
        "The report tracks {series:metrics} for every release.",
        "We measured {series:metrics} before and after the change and saw no difference.",
        "The forecast predicted {series:weather} over the weekend, so we stayed in.",
        "The coast saw {pair:weather} on Saturday night.",
        "The club offers {series:activities} on weekday evenings.",
        "Her weekends are full of {series:activities}, and she rarely sits down.",
        "The retreat includes {series:activities}, with a long lunch each day.",
        "My grandfather loves {pair:activities}, even in winter.",
        "The new office feels {series:roomadjs} compared with the old one.",
        "The hotel room was {series:roomadjs}, and we slept well.",
        "Her reply was {pair:manneradjs} and I appreciated that.",
        "After breakfast the twins {series:chores} before anyone else woke up.",
        "On Saturday I {series:chores}, and then took the dog for a long walk.",
        "Dad {pair:chores} all by himself while we were out.",
        "The verge outside our house is full of {series:flowers} in May.",
        "She planted {series:flowers} along the fence last autumn.",
        "The interview board included {series:roles} as well as two students.",
        "The visitors spoke with {pair:roles} before the tour began.",
    ]

    /// Held-out frames, disjoint from ``seriesFramesTrain``.
    static let seriesFramesTest: [String] = [
        "The exchange students came from {series:places} and stayed with host families.",
        "{series:people} will lead the workshop after lunch.",
        "My brother keeps {series:snacks} in his desk drawer.",
        "The rangers carried {series:gear} up the ridge at dawn.",
        "Our nephew enjoys {series:sports} more than his homework.",
        "The degree covers {series:subjects} in the first year.",
        "The photographer captured {series:animals} at the water hole.",
        "{series:cuisines} cooking classes run every second Thursday.",
        "{pair:teams} met in the final last spring.",
        "The translator works in {series:languages} for the council.",
        "The roofer left {series:tools} on the landing.",
        "The market garden supplies {series:crops} to two local restaurants.",
        "The spare room came furnished with {series:furniture}.",
        "The update touched {pair:services} and nothing else.",
        "The monitoring plan covers {series:metrics} across all regions.",
        "Forecasters expect {series:weather} for the north coast.",
        "The retirement village hosts {series:activities} every afternoon.",
        "The lounge felt {series:roomadjs} after the renovation.",
        "On Sunday we {series:chores} while the rain passed.",
        "The florist ordered {series:flowers} for the wedding in June.",
        "The board welcomed {series:roles} to its first meeting.",
        "The nursery walls were painted {series:colours} last spring.",
        "The petting zoo has {series:farmanimals} for the children to feed.",
        "His answer was {series:manneradjs} and put everyone at ease.",
        "She teaches {series:instruments} to beginners at the community hall.",
        "The coach stopped in {series:places} on the way home.",
    ]

    /// Values for each key of ``seriesFramesTrain``: plain noun phrases, no commas, no "and" or "or".
    static let seriesPoolsTrain: [String: [String]] = [
        "places": ["Coimbra", "Faro", "Seville", "Granada", "Bergen", "Tromso", "Kyoto", "Osaka", "Hanoi", "Cusco", "Quito", "Nairobi", "Arusha", "Windhoek", "Tallinn", "Riga"],
        "people": ["Amira", "Bruno", "Celia", "Dmitri", "Elena", "Farid", "Greta", "Hamza", "Imani", "Jonas", "Kavita", "Lukas", "Marisol", "Nadia", "Oskar", "Petra"],
        "snacks": ["popcorn", "pretzels", "dried mango", "rice crackers", "salted almonds", "banana chips", "cheese straws", "flapjacks", "fruit leather", "trail mix", "oat biscuits", "peanut brittle", "sesame bars", "corn chips", "shortbread"],
        "gear": ["the tent pegs", "the stove", "the head torch", "the map", "the water filter", "the compass", "the rope", "the gas canister", "the thermos", "the trekking poles", "the sleeping mats", "the rain jackets", "the spare laces", "the whistle"],
        "sports": ["basketball", "bowls", "squash", "canoeing", "archery", "volleyball", "cricket", "rugby", "badminton", "judo", "fencing", "handball", "diving", "sailing"],
        "subjects": ["geography", "physics", "art", "media studies", "drama", "classics", "economics", "literature", "statistics", "psychology", "textiles", "philosophy", "law", "sociology"],
        "animals": ["foxes", "herons", "otters", "badgers", "kingfishers", "hedgehogs", "owls", "deer", "hares", "seals", "dolphins", "swans", "lizards", "bats"],
        "colours": ["teal", "mustard yellow", "dusty pink", "forest green", "navy", "burnt orange", "cream", "charcoal", "sage", "lilac", "maroon", "turquoise", "olive", "copper"],
        "instruments": ["the cello", "the flute", "the piano", "the clarinet", "the oboe", "the harp", "the trumpet", "the viola", "the accordion", "the trombone", "the ukulele", "the bassoon", "the banjo", "the mandolin"],
        "cuisines": ["Thai", "Ethiopian", "Lebanese", "Peruvian", "Georgian", "Malaysian", "Moroccan", "Greek", "Indonesian", "Brazilian", "Nepalese", "Filipino", "Mexican", "Caribbean"],
        "teams": ["Riverside Rovers", "Northgate United", "Harbour City", "Eastfield Athletic", "Westbrook Wanderers", "Kingsley Town", "Ashford Rangers", "Millbank Swifts", "Oakley Park", "Redhill Royals", "Stonebridge", "Fairview Falcons", "Highcliff Hawks", "Brookside Bears"],
        "languages": ["Spanish", "Tamil", "Portuguese", "Polish", "Swahili", "Hindi", "Korean", "Turkish", "Dutch", "Arabic", "Hungarian", "Swedish", "Vietnamese", "Finnish"],
        "tools": ["the drill", "the spirit level", "the hacksaw", "the claw hammer", "the tape measure", "the chisel", "the sander", "the pliers", "the socket set", "the mallet", "the wire cutters", "the stud finder", "the bench clamp", "the file"],
        "crops": ["potatoes", "runner beans", "leeks", "courgettes", "beetroot", "sweetcorn", "kale", "onions", "radishes", "pumpkins", "garlic", "carrots", "rhubarb", "parsnips"],
        "furniture": ["a sofa", "a bookcase", "a dining table", "a wardrobe", "a desk lamp", "an armchair", "a coffee table", "a bunk bed", "a sideboard", "a rug", "a standing desk", "a bedside cabinet", "a pair of stools", "a shoe rack"],
        "services": ["the invoicing service", "the search index", "the login page", "the mail queue", "the image resizer", "the reporting job", "the payment gateway", "the notification service", "the export tool", "the cache layer", "the file uploader", "the audit log", "the scheduler", "the user directory"],
        "metrics": ["latency", "error rates", "memory use", "disk usage", "response times", "CPU load", "queue depth", "cache hits", "page weight", "startup time", "build duration", "uptime", "test coverage", "battery drain"],
        "weather": ["heavy rain", "strong winds", "hail", "thick fog", "frost", "sleet", "drizzle", "thunder", "gales", "snow showers", "black ice", "low cloud", "scattered showers", "damp mist"],
        "activities": ["hiking", "baking", "pottery", "choir practice", "chess", "sewing", "birdwatching", "yoga", "watercolours", "quiz nights", "gardening", "woodwork", "book swaps", "dance lessons"],
        "roomadjs": ["compact", "bright", "calm", "spacious", "dated", "cosy", "plain", "tidy", "cramped", "airy", "quiet", "cluttered", "sunny", "warm"],
        "manneradjs": ["polite", "friendly", "brief", "honest", "clear", "prompt", "patient", "thoughtful", "courteous", "upbeat", "direct", "gracious", "sincere", "modest"],
        "farmanimals": ["sheep", "goats", "pigs", "ducks", "geese", "cows", "turkeys", "donkeys", "ponies", "hens", "llamas", "rabbits", "alpacas", "shire horses"],
        "chores": ["swept the porch", "watered the ferns", "washed the car", "folded the laundry", "emptied the bins", "wiped the windows", "mopped the kitchen", "stacked the firewood", "cleaned the gutters", "raked the leaves", "painted the fence", "fed the chickens", "tidied the garage", "mowed the lawn"],
        "flowers": ["tulips", "daffodils", "foxgloves", "lavender", "sweet peas", "marigolds", "hollyhocks", "primroses", "dahlias", "poppies", "irises", "cornflowers", "snowdrops", "peonies"],
        "roles": ["the head teacher", "the nurse manager", "the secretary", "a local farmer", "the vicar", "the librarian", "the site engineer", "a retired judge", "the youth worker", "the harbour master", "the pharmacist", "the postmaster", "the ward sister", "a bus driver"],
    ]

    /// Held-out values, same keys as ``seriesPoolsTrain`` and disjoint from its values.
    static let seriesPoolsTest: [String: [String]] = [
        "places": ["Valencia", "Ghent", "Bruges", "Lima", "Kampala", "Ljubljana", "Zagreb", "Bologna", "Sapporo"],
        "people": ["Anil", "Beatrix", "Cormac", "Dalia", "Emeka", "Freya", "Gianni", "Hana", "Ivo"],
        "snacks": ["crisps", "liquorice", "cashews", "plain wafers", "pistachios", "granola bars", "toffee", "date balls"],
        "gear": ["the crampons", "the harness", "the bivvy bag", "the binoculars", "the camp chairs", "the solar charger", "the helmet", "the ice axe"],
        "sports": ["baseball", "curling", "lacrosse", "water polo", "table tennis", "karate", "softball", "climbing"],
        "subjects": ["astronomy", "geology", "accounting", "linguistics", "archaeology", "engineering", "nutrition", "anthropology"],
        "animals": ["zebras", "giraffes", "pelicans", "wallabies", "meerkats", "flamingos", "tortoises", "penguins"],
        "colours": ["coral", "indigo", "lemon", "plum", "peach", "slate grey", "emerald", "ochre"],
        "instruments": ["the violin", "the saxophone", "the drums", "the double bass", "the guitar", "the piccolo", "the harmonica", "the tuba"],
        "cuisines": ["Ghanaian", "Colombian", "Uzbek", "Persian", "Cuban", "Jamaican", "Egyptian", "Tunisian"],
        "teams": ["Lakeside United", "Cedar Vale", "Foxhill Rovers", "Dunmore Athletic", "Greenway Gulls", "Pinewood Town", "Silverton Stars", "Bridgeport Bulls"],
        "languages": ["Romanian", "Japanese", "Mandarin", "Russian", "Czech", "Bengali", "Urdu", "Hebrew"],
        "tools": ["the jigsaw", "the crowbar", "the set square", "the plane", "the soldering iron", "the wrench", "the staple gun", "the screwdrivers"],
        "crops": ["apples", "pears", "plums", "cherries", "tomatoes", "cucumbers", "strawberries", "peas"],
        "furniture": ["a recliner", "a dresser", "an ottoman", "a hall mirror", "a filing cabinet", "a garden bench", "a cot", "a futon"],
        "services": ["the checkout flow", "the message broker", "the admin console", "the metrics store", "the backup job", "the mobile API", "the status page", "the sync worker"],
        "metrics": ["throughput", "bounce rate", "retention", "packet loss", "crash counts", "login failures", "conversion rates", "cold start times"],
        "weather": ["bright sunshine", "light breezes", "patchy cloud", "dust storms", "freezing rain", "humid nights", "blizzards", "warm spells"],
        "activities": ["kayaking", "knitting", "life drawing", "pilates", "cycling", "board games", "bread making", "storytelling"],
        "roomadjs": ["elegant", "gloomy", "stuffy", "modern", "bare", "rustic", "cheerful", "draughty"],
        "manneradjs": ["tactful", "cordial", "gentle", "earnest", "generous", "candid", "kind", "diplomatic"],
        "farmanimals": ["lambs", "calves", "horses", "piglets", "oxen", "guinea fowl", "bulls", "peacocks"],
        "chores": ["changed the bulbs", "dusted the shelves", "ironed the shirts", "cleared the drains", "scrubbed the tiles", "pruned the roses", "polished the taps", "hung the curtains"],
        "flowers": ["roses", "sunflowers", "lilies", "carnations", "orchids", "hyacinths", "zinnias", "asters"],
        "roles": ["the coroner", "the optician", "a paramedic", "the lifeguard", "the caretaker", "a park ranger", "the registrar", "the bookkeeper"],
    ]

    /// Finished sentences with a colon that introduces a single statement, never a list.
    static let colonSentencesTrain: [String] = [
        "The cause was mundane: we ran out of time.",
        "Heads up: the office closes early on Friday.",
        "Good news: the quote came in under budget.",
        "The verdict was clear: the roof must be replaced.",
        "The plan has one flaw: nobody owns the rollout.",
        "Watch your step: the trail gets muddy after rain.",
        "Bad news: the flight has been delayed by two hours.",
        "One last thing: please lock the door when you leave.",
        "Update: the server is back online.",
        "Apologies for the noise: the builders start at seven.",
        "Here is the catch: the discount only applies online.",
        "In short: we move the launch to March.",
        "There is one thing I know: she never forgets a birthday.",
        "The rule is clear: visitors sign in at reception.",
        "Library notice: the books are due on Monday.",
        "Important: the meeting room has moved to level two.",
        "Result: the new build passes every test.",
        "My advice: sleep on it before you reply.",
        "She had one request: keep the garden as it is.",
        "To summarise: the budget is fine and the schedule is tight.",
        "The question is fair: who pays for the repairs?",
        "His excuse was the usual one: the alarm did not go off.",
        "Congratulations: you got the job.",
        "Another thing: the printer is out of toner again.",
        "The message was brief: call me when you land.",
        "The lesson was obvious: test before you ship.",
        "Verdict: the soup needs more salt.",
        "Thanks for waiting: the doctor will see you now.",
        "Sorry about the delay: the courier went to the wrong address.",
        "The conclusion is hard to avoid: the old model was better.",
        "Decision: we keep the current supplier.",
        "There was only one problem: the key did not fit.",
        "Mum's message was clear: dinner is at six.",
        "The forecast is in: it will rain all weekend.",
        "Observation: the queue is shortest before nine.",
        "A gentle nudge: the survey closes tonight.",
    ]

    /// Held-out colon sentences, disjoint from ``colonSentencesTrain``.
    static let colonSentencesTest: [String] = [
        "The hard part is obvious: we have no budget left.",
        "Good to know: the pool opens at six.",
        "Sorry for the confusion: the session has moved to Thursday.",
        "Her only condition was this: no surprises.",
        "Spoiler: the train was late again.",
        "Final answer: we are going with the blue one.",
        "Something odd happened: the lights flickered twice.",
        "Short version: the audit went well.",
        "Bad luck: the match was called off at half time.",
        "My guess is a short one: the cable is loose.",
        "Thank you all: the fundraiser beat its target.",
        "The feedback was kind: the judges loved the design.",
    ]
}
