import Foundation

/// Frames for corrections said inside a mention ("languages like Kotlin, sorry, not Kotlin, Swift")
/// and for ordinary contrasts that must stay exactly as said ("three tables, not four").
extension DeepLayoutFrames {
    // MARK: - Corrections inside a mention

    /// Finished sentences with exactly one `{X:key}` slot. The generator puts "OLD, sorry, not OLD,
    /// NEW" in the slot to build the spoken text and NEW alone to build the expected text, so each
    /// frame reads right for any two values of its pool (no "a" or "an" before the slot).
    static let mentionFramesTrain: [String] = [
        "Backend languages like {X:languages} suit the new billing service.",
        "Our new hires usually start by learning {X:languages} in their first month.",
        "For the command line tool, I'd go with something like {X:languages}.",
        "Our regional office is moving to {X:cities} next spring.",
        "The touring exhibition visits cities such as {X:cities} every summer.",
        "Please route the shipment through {X:cities} before the weekend.",
        "Our cousins live in {X:cities}, so we visit every Christmas.",
        "Someone from the {X:teams} team should review the proposal.",
        "The {X:teams} team has offered to host the next retrospective.",
        "Please hand the forms to the {X:roles} before you leave.",
        "The {X:roles} will sign off the expenses on Thursday.",
        "Ask the {X:roles} whether the side door is still locked overnight.",
        "We should call the {X:trades} about the gutters this week.",
        "The {X:trades} can start on the extension in early June.",
        "Pack extras like {X:supplies} in the side pocket of the rucksack.",
        "The volunteers will need things such as {X:supplies} for the long weekend.",
        "Teachers often rely on {X:aids} to keep lessons on track.",
        "We've been testing tools like {X:aids} with the support team.",
        "Topics like {X:topics} come up in almost every planning meeting.",
        "The workshop will cover {X:topics} in some detail.",
        "Several speakers will address issues including {X:topics}.",
        "Our help desk fields tickets about {X:topics} most days.",
        "The school offers {X:sports} after class on weekdays.",
        "Children who enjoy sports like {X:sports} are welcome to join the club.",
        "Our club runs a beginners' course in {X:sports} every spring.",
        "We're serving {X:dishes} at the fundraiser on Sunday.",
        "Dishes like {X:dishes} keep well in the freezer for weeks.",
        "The volunteers prepared {X:dishes} for the care home.",
        "We chose {X:colours} for the front door and the shutters.",
        "Shades like {X:colours} work better in a north-facing room.",
        "We're repainting the hallway in {X:colours} over the holidays.",
        "The pottery class meets on {X:days} at the community centre.",
        "The clinic will be closed on {X:days} for staff training.",
        "The food bank opens on {X:days} for new registrations.",
        "The stall needs {X:counts} volunteers for the morning shift.",
        "We've invited {X:counts} families to the open day.",
        "The van can carry {X:counts} passengers at most.",
        "The new bench should be built from {X:materials} rather than plastic.",
        "Materials like {X:materials} hold up well against the coastal weather.",
        "Her sculptures in {X:materials} sold out at the spring fair.",
        "She plays the {X:instruments} in the school orchestra.",
        "He has been learning the {X:instruments} since last winter.",
        "Please attach the {X:papers} to the application form.",
        "Finance needs the signed {X:papers} before the quarter closes.",
        "I'd cut words like {X:words} from the opening paragraph.",
        "Please tell the nurse about conditions such as {X:conditions} before the trip.",
        "Patients with {X:conditions} can book a longer appointment.",
    ]

    static let mentionFramesTest: [String] = [
        "Most of our data pipelines are written in {X:languages}.",
        "The annual meetup moves to {X:cities} in the autumn.",
        "Requests for new laptops go through the {X:teams} team.",
        "Could you forward this to the {X:roles} when you get a chance?",
        "For the overnight trek we'll need {X:supplies} and plenty of water.",
        "Our tutors have started using {X:aids} in the evening sessions.",
        "Our next seminar is about {X:topics} for small businesses.",
        "Anyone keen on {X:sports} can sign up at reception.",
        "We'll be cooking {X:dishes} for the street party.",
        "The nursery will be painted {X:colours} this time.",
        "Her daughter is taking lessons on the {X:instruments} at the music centre.",
        "The committee agreed on {X:counts} new benches for the park.",
        "The garden gate is being rebuilt in {X:materials}.",
        "The form asks about issues like {X:conditions} in the first section.",
        "Formal emails rarely need words such as {X:words}.",
        "The market runs on {X:days} between April and October.",
        "Remember to bring the {X:papers} to the office.",
        "Could the {X:trades} come round before the weekend?",
    ]

    static let mentionPoolsTrain: [String: [String]] = [
        "languages": ["Kotlin", "Swift", "Ruby", "Java", "Haskell", "Elixir", "Scala", "Lua", "Perl", "Dart", "Zig", "Groovy"],
        "cities": ["Vienna", "Prague", "Kyoto", "Denver", "Cairo", "Oslo", "Lima", "Graz", "Hanoi", "Dublin", "Seoul", "Madrid", "Nairobi"],
        "teams": ["design", "payments", "security", "data", "mobile", "support", "legal", "finance", "recruiting", "platform", "marketing", "facilities"],
        "roles": ["supervisor", "registrar", "librarian", "caretaker", "receptionist", "headteacher", "secretary", "chairperson", "pharmacist", "auditor", "coordinator", "site manager"],
        "trades": ["roofer", "tiler", "glazier", "joiner", "bricklayer", "locksmith", "decorator", "gardener", "mechanic", "plasterer", "carpenter", "welder"],
        "supplies": ["tape", "torches", "blankets", "flasks", "rope", "flares", "whistles", "tarps", "gloves", "batteries", "ponchos", "lanterns"],
        "aids": ["spreadsheets", "whiteboards", "checklists", "templates", "dashboards", "wikis", "flowcharts", "timesheets", "surveys", "rubrics", "worksheets", "flashcards"],
        "topics": ["budgeting", "hiring", "onboarding", "security", "pricing", "forecasting", "testing", "branding", "sponsorship", "fundraising", "safeguarding", "parking"],
        "sports": ["rowing", "archery", "squash", "badminton", "volleyball", "rugby", "swimming", "cycling", "fencing", "judo", "softball", "karate"],
        "dishes": ["lasagne", "dumplings", "curry", "paella", "risotto", "chilli", "tacos", "pancakes", "stew", "kebabs", "noodles", "pasta bake"],
        "colours": ["teal", "navy", "olive", "maroon", "ivory", "charcoal", "amber", "lavender", "crimson", "beige", "mustard", "turquoise"],
        "days": ["Monday morning", "Tuesday evening", "Wednesday afternoon", "Thursday morning", "Friday evening", "Saturday morning", "Sunday afternoon", "Monday evening", "Tuesday afternoon", "Wednesday morning", "Thursday evening", "Friday afternoon"],
        "counts": ["two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "twelve", "fifteen", "twenty"],
        "materials": ["oak", "pine", "bamboo", "steel", "walnut", "birch", "cedar", "maple", "concrete", "glass", "copper", "brick"],
        "instruments": ["violin", "cello", "flute", "clarinet", "trumpet", "oboe", "harp", "drums", "piano", "trombone", "saxophone", "viola"],
        "papers": ["permit", "receipt", "contract", "timetable", "brochure", "manual", "warranty", "seating plan", "itinerary", "quote", "statement", "licence"],
        "words": ["basically", "literally", "obviously", "honestly", "simply", "clearly", "essentially", "totally", "really", "quite", "just", "very"],
        "conditions": ["asthma", "eczema", "migraines", "hay fever", "diabetes", "epilepsy", "allergies", "arthritis", "anaemia", "insomnia", "vertigo", "tinnitus"],
    ]

    static let mentionPoolsTest: [String: [String]] = [
        "languages": ["TypeScript", "Erlang", "Clojure", "Julia", "Fortran", "Cobol", "Nim", "OCaml"],
        "cities": ["Toronto", "Krakow", "Bergen", "Malmo", "Lyon", "Accra", "Quito", "Tallinn"],
        "teams": ["sales", "infrastructure", "quality", "research", "training", "operations", "compliance", "editorial"],
        "roles": ["bursar", "dean", "concierge", "warden", "archivist", "principal", "steward", "counsellor"],
        "trades": ["stonemason", "chimney sweep", "fencer", "landscaper", "scaffolder", "upholsterer", "painter", "thatcher"],
        "supplies": ["tents", "sleeping bags", "compasses", "matches", "maps", "stoves", "headlamps", "radios"],
        "aids": ["calendars", "handouts", "posters", "slideshows", "diagrams", "glossaries", "textbooks", "models"],
        "topics": ["recycling", "inclusion", "scheduling", "compliance", "nutrition", "mentoring", "taxation", "volunteering"],
        "sports": ["golf", "tennis", "climbing", "diving", "baseball", "skiing", "sailing", "surfing"],
        "dishes": ["burritos", "falafel", "pies", "casserole", "samosas", "sushi", "meatballs", "pizza"],
        "colours": ["coral", "lilac", "burgundy", "sage green", "cream", "rust", "indigo", "peach"],
        "days": ["Sunday morning", "Saturday afternoon", "Sunday evening", "Monday afternoon", "Tuesday morning", "Wednesday evening", "Thursday afternoon", "Friday morning"],
        "counts": ["eleven", "thirteen", "fourteen", "sixteen", "eighteen", "twenty-five", "thirty", "forty"],
        "materials": ["ash", "teak", "aluminium", "granite", "slate", "cork", "bronze", "stone"],
        "instruments": ["guitar", "bassoon", "tuba", "piccolo", "accordion", "harmonica", "banjo", "recorder"],
        "papers": ["voucher", "leaflet", "waiver", "certificate", "rota", "booklet", "invoice", "handbook"],
        "words": ["frankly", "surely", "apparently", "definitely", "virtually", "seriously", "merely", "truly"],
        "conditions": ["bronchitis", "sinusitis", "back pain", "colour blindness", "dyslexia", "shingles", "gout", "acne"],
    ]

    // MARK: - Ordinary contrasts that stay as said

    /// Finished sentences with slots `{A:key}` and `{B:key}` (two different values of one pool) that
    /// state a plain contrast. The word "not" is part of what was meant, so nothing is removed.
    static let contrastFramesTrain: [String] = [
        "We booked {A:counts} tables for the party, not {B:counts}.",
        "The class has {A:counts} students this term, not {B:counts}.",
        "It costs {A:counts} dollars to enter, not {B:counts}.",
        "The pilot ran for {A:counts} weeks, not {B:counts}.",
        "There are {A:counts} steps up to the loft, not {B:counts}.",
        "The inspection is on {A:days}, not {B:days}.",
        "Collection happens on {A:days}, not {B:days}, in our street.",
        "I asked for the {A:colours} folders, not the {B:colours} ones.",
        "She wore {A:colours}, not {B:colours}, to the interview.",
        "The shirts should be {A:colours}, not {B:colours}.",
        "Use {A:words} here, not {B:words}.",
        "Write {A:words} in the heading, not {B:words}.",
        "Our flight lands in {A:cities}, not {B:cities}.",
        "Our summer conference will be in {A:cities}, not {B:cities}, this year.",
        "Please address the letter to {A:names}, not {B:names}.",
        "I'm meeting {A:names} on Friday, not {B:names}.",
        "The award went to {A:names}, not {B:names}.",
        "Ask {A:names} about the rota, not {B:names}.",
        "We're holding the party in the {A:venues}, not the {B:venues}.",
        "The rehearsal takes place in the {A:venues}, not the {B:venues}.",
        "We should take the {A:transport}, not the {B:transport}.",
        "The airport transfer is by {A:transport}, not {B:transport}.",
        "The talk is about {A:subjects}, not {B:subjects}.",
        "Our training day focuses on {A:subjects}, not {B:subjects}.",
        "Saturday mornings are for {A:sports}, not {B:sports}.",
        "The kids signed up for {A:sports}, not {B:sports}.",
        "We used {A:materials}, not {B:materials}, for the frame.",
        "She plays the {A:instruments}, not the {B:instruments}.",
        "The photographer arrives on the {A:dates}, not the {B:dates}.",
        "The gates close at {A:times}, not {B:times}.",
        "We'll meet at {A:times}, not {B:times}, outside the station.",
    ]

    static let contrastFramesTest: [String] = [
        "Only {A:counts} seats are free, not {B:counts}.",
        "The courier comes on {A:days}, not {B:days}.",
        "The walls are {A:colours}, not {B:colours}, in the photos.",
        "The sign should say {A:words}, not {B:words}.",
        "Our new office is in {A:cities}, not {B:cities}.",
        "Please invite {A:names}, not {B:names}, to the review.",
        "The quiz will be held in the {A:venues}, not the {B:venues}.",
        "The class trip goes by {A:transport}, not {B:transport}.",
        "Tomorrow's seminar covers {A:subjects}, not {B:subjects}.",
        "The ceremony begins at {A:times}, not {B:times}.",
        "Her birthday is on the {A:dates}, not the {B:dates}.",
        "The bench is made of {A:materials}, not {B:materials}.",
    ]

    static let contrastPoolsTrain: [String: [String]] = [
        "counts": ["two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "twelve", "fifteen", "twenty"],
        "days": ["Monday morning", "Tuesday evening", "Wednesday afternoon", "Thursday morning", "Friday evening", "Saturday morning", "Sunday afternoon", "Monday evening", "Tuesday afternoon"],
        "colours": ["teal", "navy", "olive", "maroon", "ivory", "charcoal", "amber", "lavender", "crimson"],
        "words": ["principal", "principle", "stationary", "stationery", "complement", "compliment", "loose", "lose", "cite", "site"],
        "cities": ["Vienna", "Prague", "Kyoto", "Denver", "Cairo", "Oslo", "Lima", "Graz", "Hanoi"],
        "names": ["Keiko", "Tomas", "Elena", "Marcus", "Yusuf", "Hana", "Declan", "Freya", "Mateo", "Lars"],
        "venues": ["hall", "garden", "canteen", "gym", "foyer", "courtyard", "studio", "annexe"],
        "transport": ["bus", "train", "tram", "ferry", "taxi", "coach", "bike", "scooter"],
        "subjects": ["pricing", "hiring", "testing", "marketing", "security", "budgeting", "forecasting", "onboarding"],
        "sports": ["rowing", "archery", "squash", "badminton", "volleyball", "rugby", "swimming", "cycling"],
        "materials": ["oak", "pine", "bamboo", "steel", "walnut", "birch", "cedar", "maple"],
        "instruments": ["violin", "cello", "flute", "clarinet", "trumpet", "oboe", "harp", "piano"],
        "dates": ["third", "fifth", "ninth", "twelfth", "fourteenth", "seventeenth", "twentieth", "twenty-third"],
        "times": ["quarter past seven", "half past eight", "quarter to nine", "half past ten", "quarter past eleven", "quarter to twelve", "half past one", "quarter past two"],
    ]

    static let contrastPoolsTest: [String: [String]] = [
        "counts": ["eleven", "thirteen", "fourteen", "sixteen", "eighteen", "twenty-five", "thirty"],
        "days": ["Sunday morning", "Saturday afternoon", "Sunday evening", "Monday afternoon", "Tuesday morning", "Wednesday evening", "Thursday afternoon", "Friday morning"],
        "colours": ["coral", "lilac", "burgundy", "sage green", "cream", "rust", "indigo", "peach"],
        "words": ["breach", "breech", "capital", "capitol", "farther", "further", "adapt", "adopt"],
        "cities": ["Toronto", "Krakow", "Bergen", "Malmo", "Lyon", "Accra", "Quito", "Tallinn"],
        "names": ["Oscar", "Leila", "Dmitri", "Nadia", "Felix", "Sanjay", "Jonas", "Tessa"],
        "venues": ["atrium", "chapel", "loft", "lounge", "cellar", "terrace"],
        "transport": ["minibus", "van", "monorail", "rickshaw", "metro", "cab"],
        "subjects": ["recycling", "taxation", "scheduling", "compliance", "logistics", "procurement"],
        "times": ["quarter to three", "half past four", "quarter past five", "quarter to six", "half past six", "quarter to seven"],
        "dates": ["second", "sixth", "eighth", "tenth", "eleventh", "nineteenth", "twenty-fifth"],
        "materials": ["ash", "teak", "aluminium", "granite", "slate", "cork", "bronze", "stone"],
    ]
}
