//! Text operations with the semantics of Swift's `String`, in which the Mac app's text rules are
//! written, so both apps split, compare and case text the same way.
//!
//! - A character is an extended grapheme cluster, as Swift's `Character` is; here it is the
//!   `&str` holding it. "e" followed by a combining acute accent is one character.
//! - A character's properties (letter, number, whitespace, punctuation) are its first scalar's,
//!   as `Character.isLetter` and the rest read them. Upper and lower case follow `Character`'s
//!   rules for characters of several scalars.
//! - Strings and characters are equal when they are canonically equivalent, as Swift's `==`,
//!   `Set` and `Dictionary` treat them: "é" written as one scalar equals "e" and U+0301. Keys of
//!   maps go through [`canonical_key`] for the same reason.
//! - Case mappings are Unicode's full mappings, scalar by scalar and without context, as
//!   `String.lowercased()` does: "ß" uppercases to "SS", and a final sigma is not special.
//! - Trimming works on scalars, with Foundation's character sets ([`CharacterSet`]).
//!
//! These were checked against the Swift runtime on macOS, scalar by scalar: white space,
//! punctuation, symbols, case properties and mappings, emoji properties and the grapheme breaks
//! of the golden inputs all match Rust's Unicode data. Where Swift differs, the scalars are
//! listed in `swift_string/tables.rs`, generated by `tools/swift-character-tables.swift`.

use std::borrow::Cow;
use std::ops::Range;

use unicode_normalization::{IsNormalized, UnicodeNormalization, is_nfc_quick};
use unicode_properties::{EmojiStatus, GeneralCategory, GeneralCategoryGroup, UnicodeEmoji, UnicodeGeneralCategory};
use unicode_segmentation::UnicodeSegmentation;

mod search;
mod tables;

pub use search::{ranges_of, replacing_occurrences};

// MARK: - Characters

/// The characters of `text`, in order.
pub fn characters(text: &str) -> unicode_segmentation::Graphemes<'_> {
    text.graphemes(true)
}

/// The characters of `text` with the byte offset each starts at.
pub fn character_indices(text: &str) -> unicode_segmentation::GraphemeIndices<'_> {
    text.grapheme_indices(true)
}

/// The number of characters in `text`, as `String.count`.
pub fn character_count(text: &str) -> usize {
    characters(text).count()
}

pub fn first_character(text: &str) -> Option<&str> {
    characters(text).next()
}

pub fn last_character(text: &str) -> Option<&str> {
    characters(text).next_back()
}

/// `text` without its first `count` characters, as `dropFirst(_:)`.
pub fn drop_first(text: &str, count: usize) -> &str {
    match character_indices(text).nth(count) {
        Some((start, _)) => &text[start..],
        None => "",
    }
}

/// `text` without its last `count` characters, as `dropLast(_:)`.
pub fn drop_last(text: &str, count: usize) -> &str {
    if count == 0 {
        return text;
    }
    match character_indices(text).nth_back(count - 1) {
        Some((start, _)) => &text[..start],
        None => "",
    }
}

/// The longest run of characters at the start of `text` that pass `predicate`, as `prefix(while:)`.
pub fn prefix_while(text: &str, mut predicate: impl FnMut(&str) -> bool) -> &str {
    let end = character_indices(text)
        .find(|&(_, character)| !predicate(character))
        .map_or(text.len(), |(start, _)| start);
    &text[..end]
}

/// `text` from its first character that fails `predicate`, as `drop(while:)`.
pub fn drop_while(text: &str, predicate: impl FnMut(&str) -> bool) -> &str {
    &text[prefix_while(text, predicate).len()..]
}

/// The byte offset of the first character that passes `predicate`, as `firstIndex(where:)`.
pub fn first_index(text: &str, mut predicate: impl FnMut(&str) -> bool) -> Option<usize> {
    character_indices(text)
        .find(|&(_, character)| predicate(character))
        .map(|(start, _)| start)
}

/// The byte range of the last character that passes `predicate`, as `lastIndex(where:)`.
pub fn last_index(text: &str, mut predicate: impl FnMut(&str) -> bool) -> Option<Range<usize>> {
    character_indices(text)
        .rev()
        .find(|&(_, character)| predicate(character))
        .map(|(start, character)| start..start + character.len())
}

/// Whether any character of `text` passes `predicate`, as `contains(where:)`.
pub fn any_character(text: &str, predicate: impl FnMut(&str) -> bool) -> bool {
    characters(text).any(predicate)
}

/// Whether `text` has a character equal to `character`, as `contains(_: Character)`.
pub fn contains_character(text: &str, character: &str) -> bool {
    characters(text).any(|candidate| canonically_equal(candidate, character))
}

/// Whether `character` equals one of `set`, as `Set<Character>.contains(_:)`.
pub fn is_one_of(character: &str, set: &[&str]) -> bool {
    set.iter().any(|member| canonically_equal(character, member))
}

/// Removes and returns the last character of `text`, as `removeLast()`; `None` when it is empty.
pub fn pop_last_character(text: &mut String) -> Option<String> {
    let start = character_indices(text).next_back()?.0;
    Some(text.split_off(start))
}

// MARK: - Character properties

fn first_scalar(character: &str) -> Option<char> {
    character.chars().next()
}

fn is_single_scalar(character: &str) -> bool {
    character.chars().nth(1).is_none()
}

/// `Character.isWhitespace`: the first scalar has the White_Space property. Newlines count.
pub fn is_whitespace(character: &str) -> bool {
    first_scalar(character).is_some_and(char::is_whitespace)
}

/// `Character.isNewline`.
pub fn is_newline(character: &str) -> bool {
    matches!(
        first_scalar(character),
        Some('\u{A}'..='\u{D}' | '\u{85}' | '\u{2028}' | '\u{2029}')
    )
}

/// `Character.isLetter`: the first scalar is alphabetic.
pub fn is_letter(character: &str) -> bool {
    first_scalar(character).is_some_and(is_alphabetic_scalar)
}

/// `Character.isNumber`: the first scalar has a numeric type, which includes Han numerals.
pub fn is_number(character: &str) -> bool {
    first_scalar(character).is_some_and(is_numeric_scalar)
}

/// `Character.isPunctuation`: the first scalar is in a punctuation category.
pub fn is_punctuation(character: &str) -> bool {
    first_scalar(character).is_some_and(|scalar| scalar.general_category_group() == GeneralCategoryGroup::Punctuation)
}

/// `Character.isASCII`: one ASCII scalar, or the pair CR LF.
pub fn is_ascii(character: &str) -> bool {
    character == "\r\n" || (character.len() == 1 && character.is_ascii())
}

/// `Character.isUppercase`.
pub fn is_uppercase(character: &str) -> bool {
    let Some(first) = first_scalar(character) else {
        return false;
    };
    if is_single_scalar(character) && first.is_uppercase() {
        return true;
    }
    canonically_equal(character, &uppercased(character)) && is_cased(character)
}

/// `Character.isLowercase`.
pub fn is_lowercase(character: &str) -> bool {
    let Some(first) = first_scalar(character) else {
        return false;
    };
    if is_single_scalar(character) && first.is_lowercase() {
        return true;
    }
    canonically_equal(character, &lowercased(character)) && is_cased(character)
}

/// `Character.isCased`: it has case, or casing it changes it.
pub fn is_cased(character: &str) -> bool {
    let Some(first) = first_scalar(character) else {
        return false;
    };
    if is_single_scalar(character) && is_cased_scalar(first) {
        return true;
    }
    !canonically_equal(character, &uppercased(character)) || !canonically_equal(character, &lowercased(character))
}

/// Whether the scalar is alphabetic to Swift: `Unicode.Scalar.Properties.isAlphabetic`.
pub fn is_alphabetic_scalar(scalar: char) -> bool {
    scalar.is_alphabetic() || in_table(scalar, tables::PRIVATE_USE_LETTERS)
}

/// Whether the scalar has a numeric type: `Unicode.Scalar.Properties.numericType != nil`.
pub fn is_numeric_scalar(scalar: char) -> bool {
    scalar.is_numeric() || in_table(scalar, tables::NUMBERS_OUTSIDE_NUMBER_CATEGORIES)
}

/// Unicode's Cased property: uppercase, lowercase or titlecase.
fn is_cased_scalar(scalar: char) -> bool {
    scalar.is_uppercase() || scalar.is_lowercase() || scalar.general_category() == GeneralCategory::TitlecaseLetter
}

/// `Unicode.Scalar.Properties.isEmoji`.
pub fn is_emoji_scalar(scalar: char) -> bool {
    scalar.is_emoji_char()
}

/// `Unicode.Scalar.Properties.isEmojiPresentation`: shown as an emoji without a variation selector.
pub fn is_emoji_presentation_scalar(scalar: char) -> bool {
    matches!(
        scalar.emoji_status(),
        EmojiStatus::EmojiPresentation
            | EmojiStatus::EmojiPresentationAndModifierBase
            | EmojiStatus::EmojiPresentationAndEmojiComponent
            | EmojiStatus::EmojiPresentationAndModifierAndEmojiComponent
    )
}

fn in_table(scalar: char, table: &[(char, char)]) -> bool {
    table
        .binary_search_by(|&(low, high)| {
            if high < scalar {
                std::cmp::Ordering::Less
            } else if low > scalar {
                std::cmp::Ordering::Greater
            } else {
                std::cmp::Ordering::Equal
            }
        })
        .is_ok()
}

// MARK: - Case

/// `String.lowercased()`: each scalar's full lowercase mapping.
pub fn lowercased(text: &str) -> String {
    text.chars().flat_map(char::to_lowercase).collect()
}

/// `String.uppercased()`: each scalar's full uppercase mapping.
pub fn uppercased(text: &str) -> String {
    text.chars().flat_map(char::to_uppercase).collect()
}

// MARK: - Equality

/// Whether `a` and `b` are canonically equivalent, as Swift's `==` on strings and characters.
pub fn canonically_equal(a: &str, b: &str) -> bool {
    a == b || (!(a.is_ascii() && b.is_ascii()) && a.nfc().eq(b.nfc()))
}

/// `text` in the form map keys take, so a lookup finds a key canonically equivalent to it, as
/// Swift's `Dictionary` and `Set` do.
pub fn canonical_key(text: &str) -> Cow<'_, str> {
    if is_nfc_quick(text.chars()) == IsNormalized::Yes {
        Cow::Borrowed(text)
    } else {
        Cow::Owned(text.nfc().collect())
    }
}

/// Whether `text` starts with the characters of `prefix`, as `hasPrefix(_:)`.
pub fn has_prefix(text: &str, prefix: &str) -> bool {
    let mut found = characters(text);
    characters(prefix).all(|expected| {
        found
            .next()
            .is_some_and(|character| canonically_equal(character, expected))
    })
}

/// Whether `text` ends with the characters of `suffix`, as `hasSuffix(_:)`.
pub fn has_suffix(text: &str, suffix: &str) -> bool {
    let mut found = characters(text).rev();
    characters(suffix).rev().all(|expected| {
        found
            .next()
            .is_some_and(|character| canonically_equal(character, expected))
    })
}

/// The byte range of the first occurrence of `needle` in `text` that starts and ends on
/// character boundaries, as `range(of:)`; `None` for an empty needle.
pub fn range_of(text: &str, needle: &str) -> Option<Range<usize>> {
    let wanted: Vec<&str> = characters(needle).collect();
    if wanted.is_empty() {
        return None;
    }
    let found: Vec<(usize, &str)> = character_indices(text).collect();
    found
        .windows(wanted.len())
        .find(|window| {
            window
                .iter()
                .zip(&wanted)
                .all(|(&(_, character), expected)| canonically_equal(character, expected))
        })
        .map(|window| {
            let (start, _) = window[0];
            let (last, character) = window[window.len() - 1];
            start..last + character.len()
        })
}

/// The byte range of the last occurrence of `needle` in `text` that starts and ends on character
/// boundaries, as `range(of:options: .backwards)`; `None` for an empty needle.
pub fn last_range_of(text: &str, needle: &str) -> Option<Range<usize>> {
    let wanted: Vec<&str> = characters(needle).collect();
    if wanted.is_empty() {
        return None;
    }
    let found: Vec<(usize, &str)> = character_indices(text).collect();
    found
        .windows(wanted.len())
        .rev()
        .find(|window| {
            window
                .iter()
                .zip(&wanted)
                .all(|(&(_, character), expected)| canonically_equal(character, expected))
        })
        .map(|window| {
            let (start, _) = window[0];
            let (last, character) = window[window.len() - 1];
            start..last + character.len()
        })
}

/// Whether `text` contains `needle` on character boundaries, as `contains(_: String)`.
pub fn contains_string(text: &str, needle: &str) -> bool {
    range_of(text, needle).is_some()
}

// MARK: - Splitting

/// The runs of `text` between whitespace characters, as `split(whereSeparator: \.isWhitespace)`.
pub fn split_whitespace(text: &str) -> Vec<&str> {
    split_where(text, usize::MAX, true, is_whitespace)
}

/// `text` split at each character equal to `separator`, as `split(separator:maxSplits:
/// omittingEmptySubsequences:)`.
pub fn split_on<'a>(text: &'a str, separator: &str, max_splits: usize, omitting_empty: bool) -> Vec<&'a str> {
    split_where(text, max_splits, omitting_empty, |character| {
        canonically_equal(character, separator)
    })
}

/// `text` split at each character that passes `is_separator`, as
/// `split(maxSplits:omittingEmptySubsequences:whereSeparator:)`.
pub fn split_where(
    text: &str,
    max_splits: usize,
    omitting_empty: bool,
    mut is_separator: impl FnMut(&str) -> bool,
) -> Vec<&str> {
    let mut parts = Vec::new();
    let mut start = 0;
    let mut splits = 0;
    for (index, character) in character_indices(text) {
        if splits == max_splits {
            break;
        }
        if is_separator(character) {
            if !(omitting_empty && start == index) {
                parts.push(&text[start..index]);
                splits += 1;
            }
            start = index + character.len();
        }
    }
    if !(omitting_empty && start == text.len()) {
        parts.push(&text[start..]);
    }
    parts
}

// MARK: - Trimming

/// Foundation's predefined character sets, which trim scalar by scalar.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CharacterSet {
    /// `.whitespaces`: space separators, tab and zero width space, but no newlines.
    Whitespaces,
    /// `.whitespacesAndNewlines`.
    WhitespacesAndNewlines,
    /// `.punctuationCharacters`: the punctuation categories.
    Punctuation,
    /// `.symbols`: the symbol categories.
    Symbols,
}

impl CharacterSet {
    pub fn contains(self, scalar: char) -> bool {
        match self {
            Self::Whitespaces => is_foundation_whitespace(scalar),
            Self::WhitespacesAndNewlines => {
                is_foundation_whitespace(scalar)
                    || matches!(scalar, '\u{A}'..='\u{D}' | '\u{85}' | '\u{2028}' | '\u{2029}')
            }
            Self::Punctuation => scalar.general_category_group() == GeneralCategoryGroup::Punctuation,
            Self::Symbols => scalar.general_category_group() == GeneralCategoryGroup::Symbol,
        }
    }
}

/// Foundation's `.whitespaces`, as the Swift runtime reports it.
fn is_foundation_whitespace(scalar: char) -> bool {
    matches!(
        scalar,
        '\t' | ' ' | '\u{A0}' | '\u{1680}' | '\u{2000}'..='\u{200B}' | '\u{202F}' | '\u{205F}' | '\u{3000}'
    )
}

/// `text` without the scalars of `set` at either end, as `trimmingCharacters(in:)`.
pub fn trimming(text: &str, set: CharacterSet) -> &str {
    text.trim_matches(|scalar| set.contains(scalar))
}

// MARK: - Replacing

/// `text` with every character equal to `target` replaced by `replacement`, as
/// `replacingOccurrences(of:with:)` for a single character.
pub fn replacing_character(text: &str, target: &str, replacement: &str) -> String {
    characters(text)
        .map(|character| {
            if canonically_equal(character, target) {
                replacement
            } else {
                character
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn characters_are_grapheme_clusters() {
        assert_eq!(character_count("e\u{301}"), 1);
        assert_eq!(
            characters("ශ්‍රී ලංකාව").collect::<Vec<_>>(),
            ["ශ්‍", "රී", " ", "ලං", "කා", "ව"]
        );
        assert_eq!(drop_first("e\u{301}xy", 1), "xy");
        assert_eq!(drop_last("xye\u{301}", 1), "xy");
        assert_eq!(drop_last("xy", 5), "");
        assert_eq!(last_character("ok👍🏽"), Some("👍🏽"));
    }

    #[test]
    fn properties_follow_the_first_scalar() {
        assert!(is_letter("一") && is_number("一") && is_number("万"));
        assert!(!is_number("x") && is_number("½"));
        assert!(is_letter("\u{F882}"));
        assert!(is_whitespace("\r\n") && is_newline("\r\n") && is_ascii("\r\n"));
        assert!(is_punctuation("…") && !is_punctuation("$"));
        assert!(!is_letter("☀"));
    }

    #[test]
    fn case_follows_character_rules() {
        assert!(is_lowercase("e\u{301}") && is_uppercase("E\u{301}"));
        assert!(is_cased("ǅ") && !is_uppercase("ǅ") && !is_lowercase("ǅ"));
        assert!(!is_uppercase("1") && !is_lowercase("1"));
        assert_eq!(uppercased("ß"), "SS");
        assert_eq!(lowercased("ΟΔΟΣ"), "οδοσ");
        assert_eq!(lowercased("İ"), "i\u{307}");
    }

    #[test]
    fn equality_is_canonical() {
        assert!(canonically_equal("\u{0DDC}", "\u{0DD9}\u{0DCF}"));
        assert!(canonically_equal("é", "e\u{301}"));
        assert!(is_one_of("\u{037E}", &[";"]));
        assert!(!canonically_equal("a", "b"));
        assert_eq!(canonical_key("e\u{301}"), "é");
        assert!(has_prefix("e\u{301}tude", "é"));
        assert!(!has_prefix("- \u{301}x", "- "));
        assert!(has_suffix("café", "e\u{301}"));
        assert!(has_prefix("anything", ""));
    }

    #[test]
    fn searching_respects_character_boundaries() {
        assert_eq!(range_of("say ⟦S1⟧ now", "⟦S1⟧"), Some(4..12));
        assert_eq!(range_of("⟦S1⟧\u{301}", "⟦S1⟧"), None);
        assert_eq!(range_of("abc", ""), None);
        assert!(!contains_character("x⟦\u{301}", "⟦"));
        assert!(contains_character("x⟦", "⟦"));
    }

    /// As Foundation searches backwards, checked on macOS: the last whole occurrence, so a closing
    /// tag with a combining mark on it, or with a prepended mark before it, is not one.
    #[test]
    fn searching_backwards_finds_the_last_whole_occurrence() {
        assert_eq!(last_range_of("<think>a</think>b</think>c", "</think>"), Some(17..25));
        assert_eq!(last_range_of("a</think>b</think>\u{301}c", "</think>"), Some(1..9));
        assert_eq!(last_range_of("a\u{600}</think>b", "</think>"), None);
        assert_eq!(last_range_of("x</think>", "</think>"), Some(1..9));
        assert_eq!(last_range_of("<THINK>a</THINK>", "</think>"), None);
        assert_eq!(last_range_of("abc", ""), None);
    }

    #[test]
    fn splitting_matches_swift() {
        assert_eq!(split_whitespace("  a b\u{A0}c\n d  "), ["a", "b", "c", "d"]);
        assert_eq!(split_whitespace(""), Vec::<&str>::new());
        // A combining mark on a space makes the pair whitespace, and it is dropped with it.
        assert_eq!(split_whitespace("a \u{301}b"), ["a", "b"]);
        assert_eq!(split_on("a..b.", ".", usize::MAX, false), ["a", "", "b", ""]);
        assert_eq!(split_on("a/b/c", "/", 1, false), ["a", "b/c"]);
        assert_eq!(split_on("/a", "/", usize::MAX, true), ["a"]);
    }

    #[test]
    fn trimming_uses_foundation_sets() {
        assert_eq!(trimming("\u{201C}hello\u{201D}.", CharacterSet::Punctuation), "hello");
        assert_eq!(trimming("\u{200B} a \t", CharacterSet::Whitespaces), "a");
        assert_eq!(trimming("\n a \n", CharacterSet::Whitespaces), "\n a \n");
        assert_eq!(trimming("\n a \u{2029}", CharacterSet::WhitespacesAndNewlines), "a");
        assert!(CharacterSet::Symbols.contains('+') && !CharacterSet::Symbols.contains('-'));
    }

    #[test]
    fn prefixes_and_removal() {
        assert_eq!(prefix_while("123abc", is_number), "123");
        assert_eq!(drop_while(",; x", |c| c == "," || c == ";" || is_whitespace(c)), "x");
        let mut text = String::from("ok👍🏽");
        assert_eq!(pop_last_character(&mut text).as_deref(), Some("👍🏽"));
        assert_eq!(text, "ok");
        assert_eq!(replacing_character("it\u{2019}s", "\u{2019}", "'"), "it's");
    }
}
