import Foundation

extension EmojiNames {
    /// The names people say for common emoji, in the words ``EditDistance/normalize(_:)`` gives
    /// ("e-mail" is "e mail"). They follow Unicode's short names where people use those, and add
    /// what people say instead ("thumbs up", "smiley", "tada", "lol"). Any emoji whose Unicode
    /// character name is said works without an entry here.
    ///
    /// "fireworks" is 🎆, Unicode's FIREWORKS; 🎇 is the sparkler.
    public static let commonNames: [String: String] = {
        var names: [String: String] = [:]
        for group in commonNameGroups {
            for name in group.names where names[name] == nil {
                names[name] = group.emoji
            }
        }
        return names
    }()

    /// Each emoji with the names that insert it. A name belongs to one emoji only
    /// (EmojiNamesTests checks).
    static let commonNameGroups: [(emoji: String, names: [String])] = faces + hands + hearts + celebration
        + symbols + food + objects + places + nature + animals + people

    private static let faces: [(emoji: String, names: [String])] = [
        ("\u{1F642}", ["smiley", "smiley face", "slightly smiling face", "slight smile"]),
        ("\u{1F60A}", ["smile", "smiling", "blush", "blushing", "smiling face with smiling eyes"]),
        ("\u{263A}\u{FE0F}", ["smiling face"]),
        ("\u{1F600}", ["grin", "grinning", "grinning face", "big smile"]),
        ("\u{1F604}", ["happy", "happy face", "grinning face with smiling eyes"]),
        ("\u{1F601}", ["beaming", "beaming face", "beaming face with smiling eyes"]),
        ("\u{1F602}", [
            "laugh", "laughing", "lol", "joy", "tears of joy", "face with tears of joy", "crying laughing",
            "laughing crying", "laugh cry",
        ]),
        ("\u{1F923}", ["rofl", "rolling on the floor laughing"]),
        ("\u{1F605}", ["sweat smile", "nervous laugh", "grinning face with sweat"]),
        ("\u{1F609}", ["wink", "winking", "winking face", "winky face"]),
        ("\u{1F60D}", ["heart eyes", "smiling face with heart eyes", "in love"]),
        ("\u{1F618}", ["kiss", "kissy face", "blowing a kiss", "face blowing a kiss"]),
        ("\u{1F914}", ["thinking", "thinking face", "hmm"]),
        ("\u{1F937}", ["shrug", "shrugging", "person shrugging"]),
        ("\u{1F926}", ["facepalm", "face palm", "person facepalming"]),
        ("\u{1F644}", ["eye roll", "eyeroll", "rolling eyes", "face with rolling eyes"]),
        ("\u{1F641}", ["sad", "sad face", "frown", "frowning", "unhappy", "slightly frowning face"]),
        ("\u{1F622}", ["cry", "crying", "crying face", "tear"]),
        ("\u{1F62D}", ["sob", "sobbing", "bawling", "loudly crying face"]),
        ("\u{1F620}", ["angry", "angry face", "mad"]),
        ("\u{1F621}", ["rage", "furious", "pouting face", "enraged face"]),
        ("\u{1F631}", ["scream", "screaming", "face screaming in fear"]),
        ("\u{1F62E}", ["shocked", "surprised", "wow", "open mouth", "face with open mouth"]),
        ("\u{1F60E}", ["cool", "sunglasses", "smiling face with sunglasses"]),
        ("\u{1F913}", ["nerd", "nerd face", "geek"]),
        ("\u{1F973}", ["party", "party face", "partying face"]),
        ("\u{1F92F}", ["mind blown", "exploding head"]),
        ("\u{1F917}", ["hug", "hugs", "hugging", "hugging face"]),
        ("\u{1FAE1}", ["salute", "saluting face"]),
        ("\u{1FAE0}", ["melting", "melting face"]),
        ("\u{1F643}", ["upside down", "upside down face"]),
        ("\u{1F610}", ["neutral", "neutral face", "straight face"]),
        ("\u{1F611}", ["expressionless", "expressionless face"]),
        ("\u{1F612}", ["unamused", "unamused face"]),
        ("\u{1F62C}", ["grimace", "grimacing", "grimacing face", "yikes", "awkward"]),
        ("\u{1F60C}", ["relieved", "relieved face"]),
        ("\u{1F614}", ["pensive", "pensive face"]),
        ("\u{1F61F}", ["worried", "worried face"]),
        ("\u{1F615}", ["confused", "confused face"]),
        ("\u{1F97A}", ["pleading", "pleading face", "puppy eyes", "puppy dog eyes"]),
        ("\u{1F929}", ["star struck", "starstruck"]),
        ("\u{1F60B}", ["yum", "delicious", "face savoring food", "face savouring food"]),
        ("\u{1F61B}", ["tongue", "tongue out", "stuck out tongue", "face with tongue"]),
        ("\u{1F92A}", ["zany", "zany face", "crazy", "crazy face"]),
        ("\u{1F607}", ["innocent", "halo", "angel", "smiling face with halo"]),
        ("\u{1F608}", ["devil", "smiling face with horns"]),
        ("\u{1F634}", ["sleepy", "sleeping", "sleeping face"]),
        ("\u{1F4A4}", ["zzz"]),
        ("\u{1F922}", ["sick", "nauseated", "nauseated face"]),
        ("\u{1F637}", ["mask", "face with medical mask"]),
        ("\u{1F975}", ["hot face"]),
        ("\u{1F976}", ["cold face", "freezing"]),
        ("\u{1F92B}", ["shush", "shushing face"]),
        ("\u{1F910}", ["zipper mouth", "zipper mouth face"]),
        ("\u{1F911}", ["money mouth", "money mouth face"]),
        ("\u{1F480}", ["skull"]),
        ("\u{1F47B}", ["ghost"]),
        ("\u{1F916}", ["robot"]),
        ("\u{1F47D}", ["alien"]),
        ("\u{1F921}", ["clown", "clown face"]),
        ("\u{1F4A9}", ["poop", "poo", "pile of poo"]),
        ("\u{1F648}", ["see no evil", "see no evil monkey"]),
        ("\u{1F649}", ["hear no evil", "hear no evil monkey"]),
        ("\u{1F64A}", ["speak no evil", "speak no evil monkey"]),
    ]

    private static let hands: [(emoji: String, names: [String])] = [
        ("\u{1F44D}", ["thumbs up", "thumb up"]),
        ("\u{1F44E}", ["thumbs down", "thumb down"]),
        ("\u{1F44F}", ["clap", "clapping", "clapping hands", "applause"]),
        ("\u{1F64F}", ["pray", "praying", "praying hands", "folded hands"]),
        ("\u{1F44B}", ["wave", "waving", "waving hand", "hand wave"]),
        ("\u{1F44C}", ["ok", "okay", "ok hand", "okay hand"]),
        ("\u{1F64C}", ["raised hands", "raising hands", "hands up", "hooray"]),
        ("\u{1F4AA}", ["muscle", "flex", "flexed biceps", "biceps"]),
        ("\u{1F91D}", ["handshake", "shake hands"]),
        ("\u{1F44A}", ["fist bump", "fist", "punch", "oncoming fist"]),
        ("\u{270C}\u{FE0F}", ["peace", "peace sign", "victory", "victory hand"]),
        ("\u{1F91E}", ["fingers crossed", "crossed fingers"]),
        ("\u{1F918}", ["rock on", "horns", "sign of the horns"]),
        ("\u{1F919}", ["call me", "call me hand"]),
        ("\u{1F446}", ["point up", "pointing up"]),
        ("\u{1F447}", ["point down", "pointing down"]),
        ("\u{1F448}", ["point left", "pointing left"]),
        ("\u{1F449}", ["point right", "pointing right"]),
        ("\u{270D}\u{FE0F}", ["writing hand"]),
        ("\u{1F440}", ["eyes"]),
        ("\u{1F9E0}", ["brain"]),
    ]

    private static let hearts: [(emoji: String, names: [String])] = [
        ("\u{2764}\u{FE0F}", ["heart", "red heart"]),
        ("\u{1F494}", ["broken heart", "heartbreak"]),
        ("\u{1F9E1}", ["orange heart"]),
        ("\u{1F49B}", ["yellow heart"]),
        ("\u{1F49A}", ["green heart"]),
        ("\u{1F499}", ["blue heart"]),
        ("\u{1F49C}", ["purple heart"]),
        ("\u{1F5A4}", ["black heart"]),
        ("\u{1F90D}", ["white heart"]),
        ("\u{1F90E}", ["brown heart"]),
        ("\u{1FA77}", ["pink heart"]),
        ("\u{1F496}", ["sparkling heart"]),
        ("\u{1F495}", ["two hearts"]),
    ]

    private static let celebration: [(emoji: String, names: [String])] = [
        ("\u{1F389}", ["party popper", "tada", "ta da", "confetti", "celebration"]),
        ("\u{1F38A}", ["confetti ball"]),
        ("\u{1F386}", ["fireworks", "firework"]),
        ("\u{1F387}", ["sparkler"]),
        ("\u{2728}", ["sparkles", "sparkle", "sparkly"]),
        ("\u{2B50}", ["star"]),
        ("\u{1F31F}", ["glowing star"]),
        ("\u{1F388}", ["balloon"]),
        ("\u{1F381}", ["gift", "wrapped gift"]),
        ("\u{1F382}", ["cake", "birthday cake"]),
        ("\u{1F3C6}", ["trophy"]),
        ("\u{1F947}", ["medal", "gold medal", "first place"]),
        ("\u{1F451}", ["crown"]),
        ("\u{1F4AF}", ["hundred", "one hundred", "hundred points", "100"]),
        ("\u{1F525}", ["fire", "flame", "lit"]),
        ("\u{1F680}", ["rocket"]),
        ("\u{1F48E}", ["gem", "gem stone", "diamond"]),
        ("\u{1F48D}", ["ring"]),
    ]

    private static let symbols: [(emoji: String, names: [String])] = [
        ("\u{2705}", ["check", "check mark", "checkmark", "tick", "green tick", "green check"]),
        ("\u{2714}\u{FE0F}", ["heavy check mark"]),
        ("\u{274C}", ["cross", "cross mark", "x"]),
        ("\u{26A0}\u{FE0F}", ["warning", "caution"]),
        ("\u{1F6D1}", ["stop sign"]),
        ("\u{26D4}", ["no entry"]),
        ("\u{2753}", ["question mark"]),
        ("\u{2757}", ["exclamation mark"]),
        ("\u{1F4A1}", ["light bulb", "lightbulb", "bulb"]),
        ("\u{1F512}", ["lock", "locked"]),
        ("\u{1F513}", ["unlock", "unlocked"]),
        ("\u{1F511}", ["key"]),
        ("\u{1F514}", ["bell"]),
        ("\u{1F517}", ["link"]),
        ("\u{2699}\u{FE0F}", ["gear", "cog"]),
        ("\u{1F527}", ["wrench", "spanner"]),
        ("\u{1F528}", ["hammer"]),
        ("\u{1F6E0}\u{FE0F}", ["tools", "hammer and wrench"]),
        ("\u{1F4A3}", ["bomb"]),
        ("\u{1F50D}", ["magnifying glass"]),
        ("\u{1F4AC}", ["speech bubble", "speech balloon"]),
        ("\u{1F4AD}", ["thought bubble", "thought balloon"]),
        ("\u{26A1}", ["zap", "lightning", "lightning bolt", "high voltage"]),
        ("\u{1F4A5}", ["boom", "collision", "explosion"]),
        ("\u{2B06}\u{FE0F}", ["up arrow", "arrow up"]),
        ("\u{2B07}\u{FE0F}", ["down arrow", "arrow down"]),
        ("\u{2B05}\u{FE0F}", ["left arrow", "arrow left"]),
        ("\u{27A1}\u{FE0F}", ["right arrow", "arrow right"]),
        ("\u{267B}\u{FE0F}", ["recycle", "recycling"]),
        ("\u{267E}\u{FE0F}", ["infinity"]),
        ("\u{1F198}", ["sos"]),
        ("\u{1F6A8}", ["siren", "police light", "rotating light"]),
        ("\u{1F6A7}", ["construction", "under construction"]),
        ("\u{1F6A9}", ["red flag"]),
        ("\u{1F3C1}", ["checkered flag", "chequered flag", "racing flag", "finish flag"]),
        ("\u{1F3F3}\u{FE0F}", ["white flag"]),
    ]

    private static let food: [(emoji: String, names: [String])] = [
        ("\u{2615}", ["coffee", "hot beverage"]),
        ("\u{1F375}", ["tea", "teacup"]),
        ("\u{1F37A}", ["beer", "beer mug"]),
        ("\u{1F37B}", ["beers", "cheers", "clinking beer mugs"]),
        ("\u{1F377}", ["wine", "wine glass", "red wine"]),
        ("\u{1F942}", ["clinking glasses", "toast"]),
        ("\u{1F37E}", ["champagne", "bottle with popping cork"]),
        ("\u{1F355}", ["pizza"]),
        ("\u{1F354}", ["burger", "hamburger"]),
        ("\u{1F32E}", ["taco"]),
        ("\u{1F363}", ["sushi"]),
        ("\u{1F35C}", ["noodles", "ramen"]),
        ("\u{1F96A}", ["sandwich"]),
        ("\u{1F35E}", ["bread"]),
        ("\u{1F9C0}", ["cheese"]),
        ("\u{1F95A}", ["egg"]),
        ("\u{1F36A}", ["cookie"]),
        ("\u{1F9C1}", ["cupcake"]),
        ("\u{1F369}", ["doughnut", "donut"]),
        ("\u{1F36B}", ["chocolate"]),
        ("\u{1F36C}", ["candy", "sweets"]),
        ("\u{1F366}", ["ice cream"]),
        ("\u{1F37F}", ["popcorn"]),
        ("\u{1F34E}", ["apple", "red apple"]),
        ("\u{1F34C}", ["banana"]),
        ("\u{1F951}", ["avocado"]),
        ("\u{1F349}", ["watermelon"]),
        ("\u{1F353}", ["strawberry"]),
        ("\u{1F336}\u{FE0F}", ["chili", "chilli", "hot pepper"]),
    ]

    private static let objects: [(emoji: String, names: [String])] = [
        ("\u{1F4B0}", ["money", "money bag", "moneybag"]),
        ("\u{1F4B5}", ["dollar", "dollars", "cash", "dollar bill"]),
        ("\u{1F4B8}", ["money with wings"]),
        ("\u{1F4B3}", ["credit card"]),
        ("\u{1F4C8}", ["chart", "chart up", "chart increasing", "trending up", "stonks"]),
        ("\u{1F4C9}", ["chart down", "chart decreasing", "trending down"]),
        ("\u{1F4CA}", ["bar chart", "graph"]),
        ("\u{1F4C5}", ["calendar"]),
        ("\u{23F0}", ["alarm", "alarm clock"]),
        ("\u{23F3}", ["hourglass", "hourglass not done"]),
        ("\u{23F1}\u{FE0F}", ["stopwatch", "timer"]),
        ("\u{1F4F1}", ["phone", "mobile phone", "cell phone", "smartphone"]),
        ("\u{260E}\u{FE0F}", ["telephone"]),
        ("\u{1F4BB}", ["laptop", "computer"]),
        ("\u{1F5A5}\u{FE0F}", ["desktop", "desktop computer"]),
        ("\u{2328}\u{FE0F}", ["keyboard"]),
        ("\u{1F4E7}", ["email", "e mail"]),
        ("\u{2709}\u{FE0F}", ["envelope", "mail"]),
        ("\u{1F4E5}", ["inbox", "inbox tray"]),
        ("\u{1F4E4}", ["outbox", "outbox tray"]),
        ("\u{270F}\u{FE0F}", ["pencil"]),
        ("\u{1F4DD}", ["memo", "note"]),
        ("\u{1F4CC}", ["pin", "pushpin"]),
        ("\u{1F4CD}", ["round pushpin", "location pin"]),
        ("\u{1F4CE}", ["paperclip", "paper clip"]),
        ("\u{2702}\u{FE0F}", ["scissors"]),
        ("\u{1F4D6}", ["book", "open book"]),
        ("\u{1F4DA}", ["books"]),
        ("\u{1F4F0}", ["newspaper"]),
        ("\u{1F4F7}", ["camera"]),
        ("\u{1F3AC}", ["movie", "film", "clapper board"]),
        ("\u{1F4FA}", ["tv", "television"]),
        ("\u{1F3B5}", ["music", "musical note", "music note"]),
        ("\u{1F3B6}", ["musical notes", "music notes"]),
        ("\u{1F3A7}", ["headphones", "headphone"]),
        ("\u{1F3A4}", ["microphone", "mic"]),
        ("\u{1F3B8}", ["guitar"]),
        ("\u{1F4E6}", ["package", "parcel"]),
        ("\u{1F6D2}", ["shopping cart", "shopping trolley"]),
        ("\u{1F6CD}\u{FE0F}", ["shopping bags"]),
        ("\u{1F393}", ["graduation cap"]),
        ("\u{1F4BC}", ["briefcase"]),
        ("\u{1F4C1}", ["folder", "file folder"]),
        ("\u{1F4CB}", ["clipboard"]),
        ("\u{1F5D1}\u{FE0F}", ["wastebasket", "rubbish bin", "trash can"]),
        ("\u{1F6E1}\u{FE0F}", ["shield"]),
        ("\u{1F50B}", ["battery"]),
        ("\u{1F50C}", ["plug", "electric plug"]),
        ("\u{1F48A}", ["pill"]),
    ]

    private static let places: [(emoji: String, names: [String])] = [
        ("\u{1F3E0}", ["house", "home"]),
        ("\u{1F3E2}", ["office", "office building"]),
        ("\u{1F697}", ["car", "red car", "automobile"]),
        ("\u{1F695}", ["taxi", "cab"]),
        ("\u{1F68C}", ["bus"]),
        ("\u{2708}\u{FE0F}", ["airplane", "aeroplane", "plane"]),
        ("\u{1F686}", ["train"]),
        ("\u{1F6B2}", ["bicycle", "bike"]),
        ("\u{1F6A2}", ["ship", "boat"]),
        ("\u{1F30D}", ["globe", "earth", "world"]),
        ("\u{1F5FA}\u{FE0F}", ["map", "world map"]),
        ("\u{26F0}\u{FE0F}", ["mountain"]),
        ("\u{1F3D6}\u{FE0F}", ["beach"]),
        ("\u{1F305}", ["sunrise"]),
    ]

    private static let nature: [(emoji: String, names: [String])] = [
        ("\u{2600}\u{FE0F}", ["sun", "sunny", "sunshine"]),
        ("\u{1F319}", ["moon", "crescent moon"]),
        ("\u{1F308}", ["rainbow"]),
        ("\u{2601}\u{FE0F}", ["cloud", "cloudy"]),
        ("\u{1F327}\u{FE0F}", ["rain", "rainy", "cloud with rain"]),
        ("\u{2602}\u{FE0F}", ["umbrella"]),
        ("\u{2744}\u{FE0F}", ["snowflake", "snow"]),
        ("\u{26C4}", ["snowman"]),
        ("\u{26C8}\u{FE0F}", ["thunderstorm", "thunder"]),
        ("\u{1F4A7}", ["droplet", "water drop"]),
        ("\u{1F30A}", ["ocean", "water wave"]),
        ("\u{1F339}", ["rose"]),
        ("\u{1F338}", ["flower", "blossom", "cherry blossom"]),
        ("\u{1F490}", ["bouquet", "flowers"]),
        ("\u{1F337}", ["tulip"]),
        ("\u{1F33B}", ["sunflower"]),
        ("\u{1F331}", ["seedling", "sprout"]),
        ("\u{1F333}", ["tree", "deciduous tree"]),
        ("\u{1F384}", ["christmas tree"]),
        ("\u{1F334}", ["palm tree"]),
        ("\u{1F335}", ["cactus"]),
        ("\u{1F340}", ["four leaf clover", "clover"]),
        ("\u{1F342}", ["fallen leaf"]),
        ("\u{1F383}", ["pumpkin", "jack o lantern"]),
    ]

    private static let animals: [(emoji: String, names: [String])] = [
        ("\u{1F436}", ["dog", "dog face", "puppy"]),
        ("\u{1F431}", ["cat", "cat face", "kitten", "kitty"]),
        ("\u{1F435}", ["monkey", "monkey face"]),
        ("\u{1F984}", ["unicorn"]),
        ("\u{1F41D}", ["bee", "honeybee"]),
        ("\u{1F98B}", ["butterfly"]),
        ("\u{1F41B}", ["bug", "caterpillar"]),
        ("\u{1F422}", ["turtle", "tortoise"]),
        ("\u{1F40C}", ["snail"]),
        ("\u{1F41F}", ["fish"]),
        ("\u{1F433}", ["whale"]),
        ("\u{1F42C}", ["dolphin"]),
        ("\u{1F419}", ["octopus"]),
        ("\u{1F988}", ["shark"]),
        ("\u{1F980}", ["crab"]),
        ("\u{1F426}", ["bird"]),
        ("\u{1F427}", ["penguin"]),
        ("\u{1F989}", ["owl"]),
        ("\u{1F414}", ["chicken"]),
        ("\u{1F434}", ["horse", "horse face"]),
        ("\u{1F42E}", ["cow", "cow face"]),
        ("\u{1F437}", ["pig", "pig face"]),
        ("\u{1F42D}", ["mouse", "mouse face"]),
        ("\u{1F430}", ["rabbit", "bunny", "rabbit face"]),
        ("\u{1F98A}", ["fox"]),
        ("\u{1F43B}", ["bear"]),
        ("\u{1F43C}", ["panda"]),
        ("\u{1F428}", ["koala"]),
        ("\u{1F42F}", ["tiger", "tiger face"]),
        ("\u{1F981}", ["lion"]),
        ("\u{1F438}", ["frog"]),
        ("\u{1F40D}", ["snake"]),
        ("\u{1F409}", ["dragon"]),
        ("\u{1F996}", ["dinosaur", "t rex"]),
        ("\u{1F9A5}", ["sloth"]),
        ("\u{1F418}", ["elephant"]),
        ("\u{1F577}\u{FE0F}", ["spider"]),
        ("\u{1F41C}", ["ant"]),
        ("\u{1F411}", ["sheep"]),
    ]

    private static let people: [(emoji: String, names: [String])] = [
        ("\u{1F476}", ["baby"]),
        ("\u{1F977}", ["ninja"]),
        ("\u{1F385}", ["santa", "santa claus", "father christmas"]),
        ("\u{1F9B8}", ["superhero"]),
        ("\u{1F3C3}", ["runner", "person running"]),
        ("\u{1F483}", ["dancer", "woman dancing"]),
        ("\u{1F57A}", ["man dancing"]),
        ("\u{1F465}", ["busts in silhouette"]),
        ("\u{1F464}", ["bust in silhouette"]),
        ("\u{1F9D1}\u{200D}\u{1F4BB}", ["technologist", "developer", "programmer", "coder"]),
        ("\u{26BD}", ["soccer", "soccer ball", "football"]),
        ("\u{1F3C0}", ["basketball"]),
        ("\u{1F3BE}", ["tennis"]),
        ("\u{1F3CF}", ["cricket", "cricket bat"]),
        ("\u{26F3}", ["golf"]),
        ("\u{1F3AF}", ["target", "bullseye", "direct hit", "dart"]),
        ("\u{1F3AE}", ["video game", "game controller"]),
        ("\u{1F3B2}", ["dice", "game die"]),
        ("\u{1F9E9}", ["puzzle", "puzzle piece", "jigsaw"]),
    ]
}
