import AppKit
import Foundation
import Insertion
import os

/// A pasteboard in memory, with the same change-count semantics as `NSPasteboard`.
final class FakePasteboard: PasteboardAccess {
    private struct State {
        var items: [PasteboardSnapshot.Item]
        var changeCount = 0
        var refusesWrites = false
        var transientWrites: [String] = []
        var restores = 0
    }

    private let state: OSAllocatedUnfairLock<State>

    init(items: [PasteboardSnapshot.Item] = [], refusesWrites: Bool = false) {
        state = OSAllocatedUnfairLock(initialState: State(items: items, refusesWrites: refusesWrites))
    }

    /// The pasteboard as a snapshot would see it now.
    var items: [PasteboardSnapshot.Item] { state.withLock { $0.items } }
    var transientWrites: [String] { state.withLock { $0.transientWrites } }
    var restores: Int { state.withLock { $0.restores } }

    /// The plain-text representation of the first item, as ⌘V in a text field would paste it.
    var string: String? {
        state.withLock { state in
            state.items.first?.representations
                .first { $0.type == NSPasteboard.PasteboardType.string.rawValue }
                .map { String(decoding: $0.data, as: UTF8.self) }
        }
    }

    /// Another app (or the user) copies something.
    func simulateCopy(_ text: String) {
        state.withLock { state in
            state.items = [Self.plainItem(text)]
            state.changeCount += 1
        }
    }

    var changeCount: Int { state.withLock { $0.changeCount } }

    func snapshot() -> PasteboardSnapshot {
        PasteboardSnapshot(items: items)
    }

    func restore(_ snapshot: PasteboardSnapshot) -> Bool {
        state.withLock { state in
            state.items = snapshot.items
            state.changeCount += 1
            state.restores += 1
        }
        return true
    }

    func writeTransient(_ text: String) -> Int? {
        state.withLock { state in
            state.items = []
            state.changeCount += 1
            guard !state.refusesWrites else { return nil }
            state.items = [PasteboardSnapshot.Item(representations: [
                .init(type: NSPasteboard.PasteboardType.string.rawValue, data: Data(text.utf8)),
                .init(type: SystemPasteboard.transientType.rawValue, data: Data()),
                .init(type: SystemPasteboard.autoGeneratedType.rawValue, data: Data()),
            ])]
            state.transientWrites.append(text)
            return state.changeCount
        }
    }

    func writeString(_ text: String) -> Bool {
        state.withLock { state in
            state.items = []
            state.changeCount += 1
            guard !state.refusesWrites else { return false }
            state.items = [Self.plainItem(text)]
            return true
        }
    }

    static func plainItem(_ text: String) -> PasteboardSnapshot.Item {
        PasteboardSnapshot.Item(representations: [
            .init(type: NSPasteboard.PasteboardType.string.rawValue, data: Data(text.utf8)),
        ])
    }
}

/// Records shortcuts instead of posting them, and runs what the app would do in response.
final class FakeKeystrokes: KeystrokeSender {
    private struct State {
        var pastes = 0
        var undos = 0
    }

    private let succeeds: Bool
    private let onPaste: @Sendable () -> Void
    private let onUndo: @Sendable () -> Void
    private let state = OSAllocatedUnfairLock(initialState: State())

    init(succeeds: Bool = true, onPaste: @escaping @Sendable () -> Void = {}, onUndo: @escaping @Sendable () -> Void = {}) {
        self.succeeds = succeeds
        self.onPaste = onPaste
        self.onUndo = onUndo
    }

    var pastes: Int { state.withLock { $0.pastes } }
    var undos: Int { state.withLock { $0.undos } }

    func sendPaste() -> Bool {
        guard succeeds else { return false }
        state.withLock { $0.pastes += 1 }
        onPaste()
        return true
    }

    func sendUndo() -> Bool {
        guard succeeds else { return false }
        state.withLock { $0.undos += 1 }
        onUndo()
        return true
    }

    /// Keystrokes whose ⌘V pastes the pasteboard's text into `element`, and whose ⌘Z undoes its
    /// last change, like a real app.
    static func typing(into element: FakeElement, from pasteboard: FakePasteboard) -> FakeKeystrokes {
        FakeKeystrokes(
            onPaste: { pasteboard.string.map(element.typeText) },
            onUndo: { element.undoLastChange() }
        )
    }
}

/// A scripted inserter that records what it was asked to insert.
final class FakeInserter: TextInserter {
    private let outcome: Result<NSRange?, InsertionError>
    private let calls = OSAllocatedUnfairLock(initialState: [String]())

    init(_ outcome: Result<NSRange?, InsertionError>) {
        self.outcome = outcome
    }

    var insertedTexts: [String] { calls.withLock { $0 } }

    func insert(_ text: String, into target: InsertionTarget) async throws(InsertionError) -> NSRange? {
        calls.withLock { $0.append(text) }
        return try outcome.get()
    }
}

/// A value shared between a test and a fake's callback.
final class Locked<Value: Sendable>: Sendable {
    private let lock: OSAllocatedUnfairLock<Value>

    init(_ value: Value) {
        lock = OSAllocatedUnfairLock(initialState: value)
    }

    var value: Value { lock.withLock { $0 } }

    func set(_ value: Value) {
        lock.withLock { $0 = value }
    }

    /// Changes the value in one step, so concurrent callers cannot lose each other's changes.
    func update(_ change: @Sendable (inout Value) -> Void) {
        lock.withLock { change(&$0) }
    }
}

enum Fixtures {
    static let textEdit = AppInfo(bundleIdentifier: "com.apple.TextEdit", name: "TextEdit", processIdentifier: 42)
    static let terminal = AppInfo(bundleIdentifier: "com.apple.Terminal", name: "Terminal", processIdentifier: 43)
    static let notes = AppInfo(bundleIdentifier: "com.apple.Notes", name: "Notes", processIdentifier: 44)

    static func target(
        _ element: (any AccessibilityElement)?,
        app: AppInfo? = textEdit,
        isSecure: Bool = false
    ) -> InsertionTarget {
        InsertionTarget(app: app, element: element, isSecure: isSecure, isMultiline: false, caretRect: nil)
    }
}
