import AppKit
import Foundation
import Insertion
import Testing

@Suite("PasteboardTextInserter")
struct PasteboardTextInserterTests {
    /// A clipboard holding rich text with its plain fallback, plus an image in a second item.
    private static let userClipboard = [
        PasteboardSnapshot.Item(representations: [
            .init(type: NSPasteboard.PasteboardType.rtf.rawValue, data: Data(#"{\rtf1 Bold}"#.utf8)),
            .init(type: NSPasteboard.PasteboardType.string.rawValue, data: Data("Bold".utf8)),
        ]),
        PasteboardSnapshot.Item(representations: [
            .init(type: NSPasteboard.PasteboardType.png.rawValue, data: Data([0x89, 0x50, 0x4E, 0x47])),
        ]),
    ]

    private func makeInserter(
        _ pasteboard: FakePasteboard,
        _ keystrokes: FakeKeystrokes,
        focus: FakeFocus = FakeFocus()
    ) -> PasteboardTextInserter {
        PasteboardTextInserter(pasteboard: pasteboard, keystrokes: keystrokes, focus: focus, restoreDelayMs: 0)
    }

    @Test func pastesTheTextThenRestoresEveryItemAndType() async throws {
        let pasteboard = FakePasteboard(items: Self.userClipboard)
        let field = FakeElement(value: "To: ")
        let keystrokes = FakeKeystrokes.typing(into: field, from: pasteboard)

        let range = try await makeInserter(pasteboard, keystrokes).insert("Sam", into: Fixtures.target(field))

        #expect(range == nil)
        #expect(field.value == "To: Sam")
        #expect(keystrokes.pastes == 1)
        #expect(pasteboard.transientWrites == ["Sam"])
        #expect(pasteboard.items == Self.userClipboard)
    }

    @Test func writesTheTextWithClipboardManagerMarkers() async throws {
        let pasteboard = FakePasteboard()
        let seenAtPaste = Locked<[String]>([])
        let keystrokes = FakeKeystrokes(onPaste: {
            seenAtPaste.set(pasteboard.items.first?.representations.map(\.type) ?? [])
        })

        _ = try await makeInserter(pasteboard, keystrokes).insert("text", into: Fixtures.target(nil))

        #expect(seenAtPaste.value == [
            NSPasteboard.PasteboardType.string.rawValue,
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
        ])
    }

    @Test func anEmptyClipboardIsEmptyAgainAfterPasting() async throws {
        let pasteboard = FakePasteboard()
        _ = try await makeInserter(pasteboard, FakeKeystrokes()).insert("secret plan", into: Fixtures.target(nil))
        #expect(pasteboard.items.isEmpty)
    }

    @Test func doesNotRestoreOverSomethingCopiedDuringThePaste() async throws {
        let pasteboard = FakePasteboard(items: Self.userClipboard)
        let keystrokes = FakeKeystrokes(onPaste: { pasteboard.simulateCopy("copied meanwhile") })

        _ = try await makeInserter(pasteboard, keystrokes).insert("dictated", into: Fixtures.target(nil))

        #expect(pasteboard.string == "copied meanwhile")
        #expect(pasteboard.restores == 0)
    }

    @Test func restoresTheClipboardWhenThePasteShortcutFails() async {
        let pasteboard = FakePasteboard(items: Self.userClipboard)
        let inserter = makeInserter(pasteboard, FakeKeystrokes(succeeds: false))

        await #expect(throws: InsertionError.keystrokeFailed) {
            try await inserter.insert("dictated", into: Fixtures.target(nil))
        }
        #expect(pasteboard.items == Self.userClipboard)
        #expect(pasteboard.restores == 1)
    }

    @Test func doesNotPasteWhenThePasteboardRefusesTheText() async {
        let pasteboard = FakePasteboard(items: Self.userClipboard, refusesWrites: true)
        let keystrokes = FakeKeystrokes()

        await #expect(throws: InsertionError.pasteboardWriteFailed) {
            try await makeInserter(pasteboard, keystrokes).insert("dictated", into: Fixtures.target(nil))
        }
        #expect(keystrokes.pastes == 0)
        #expect(pasteboard.items == Self.userClipboard)
    }

    @Test func waitsBeforeRestoring() async throws {
        let pasteboard = FakePasteboard(items: Self.userClipboard)
        let inserter = PasteboardTextInserter(
            pasteboard: pasteboard, keystrokes: FakeKeystrokes(), focus: FakeFocus(), restoreDelayMs: 20
        )
        let clock = ContinuousClock()
        let start = clock.now

        _ = try await inserter.insert("dictated", into: Fixtures.target(nil))

        #expect(clock.now - start >= .milliseconds(20))
        #expect(pasteboard.items == Self.userClipboard)
    }

    /// Cancelling after ⌘V must not restore early, or the app would paste the user's clipboard.
    @Test func restoresOnlyAfterTheDelayEvenWhenCancelled() async throws {
        let pasteboard = FakePasteboard(items: Self.userClipboard)
        let inserter = PasteboardTextInserter(
            pasteboard: pasteboard, keystrokes: FakeKeystrokes(), focus: FakeFocus(), restoreDelayMs: 50
        )
        let clock = ContinuousClock()
        let start = clock.now

        let task = Task { try await inserter.insert("dictated", into: Fixtures.target(nil)) }
        task.cancel()
        _ = try await task.value

        #expect(clock.now - start >= .milliseconds(50))
        #expect(pasteboard.items == Self.userClipboard)
    }

    /// A dictation finishing while *Undo AI edit* pastes: the second paste must not snapshot the
    /// first one's text and later restore it over the user's clipboard.
    @Test func overlappingPastesRunOneAtATimeAndRestoreTheUsersClipboard() async throws {
        let pasteboard = FakePasteboard(items: Self.userClipboard)
        let clipboardAtEachPaste = Locked<[String?]>([])
        let keystrokes = FakeKeystrokes(onPaste: {
            let current = pasteboard.string
            clipboardAtEachPaste.update { $0.append(current) }
        })
        let inserter = PasteboardTextInserter(
            pasteboard: pasteboard, keystrokes: keystrokes, focus: FakeFocus(), restoreDelayMs: 30
        )

        async let first = inserter.insert("first", into: Fixtures.target(nil))
        async let second = inserter.insert("second", into: Fixtures.target(nil))
        _ = try await (first, second)

        #expect(pasteboard.items == Self.userClipboard)
        #expect(Set(pasteboard.transientWrites) == ["first", "second"])
        #expect(Set(clipboardAtEachPaste.value.compactMap { $0 }) == ["first", "second"])
        #expect(pasteboard.restores == 2)
    }

    // MARK: - Focus checked again just before ⌘V

    /// The target was read before processing; the user tabbed into a password field since.
    @Test func doesNotPasteOrTouchThePasteboardWhenFocusBecameSecure() async {
        let pasteboard = FakePasteboard(items: Self.userClipboard)
        let keystrokes = FakeKeystrokes()
        let focus = FakeFocus()
        focus.move(to: Fixtures.textEdit, secure: true)

        await #expect(throws: InsertionError.focusBecameSecure) {
            try await makeInserter(pasteboard, keystrokes, focus: focus).insert("hunter2", into: Fixtures.target(nil))
        }
        #expect(keystrokes.pastes == 0)
        #expect(pasteboard.changeCount == 0, "the dictated text never reached the pasteboard")
        #expect(pasteboard.items == Self.userClipboard)
    }

    /// ⌘V would go to the app that has focus now, not the one dictated into.
    @Test func doesNotPasteIntoAnotherApp() async {
        let pasteboard = FakePasteboard(items: Self.userClipboard)
        let keystrokes = FakeKeystrokes()
        let focus = FakeFocus()
        focus.move(to: Fixtures.notes)

        await #expect(throws: InsertionError.focusMovedToAnotherApp) {
            try await makeInserter(pasteboard, keystrokes, focus: focus).insert("dictated", into: Fixtures.target(nil))
        }
        #expect(keystrokes.pastes == 0)
        #expect(pasteboard.changeCount == 0)
        #expect(pasteboard.items == Self.userClipboard)
    }

    @Test func aRelaunchOfTheSameAppIsAnotherApp() async {
        let focus = FakeFocus()
        focus.move(to: AppInfo(bundleIdentifier: "com.apple.TextEdit", name: "TextEdit", processIdentifier: 99))
        let keystrokes = FakeKeystrokes()

        await #expect(throws: InsertionError.focusMovedToAnotherApp) {
            try await makeInserter(FakePasteboard(), keystrokes, focus: focus).insert("dictated", into: Fixtures.target(nil))
        }
        #expect(keystrokes.pastes == 0)
    }

    @Test func pastesWhenFocusIsStillInTheSameApp() async throws {
        let focus = FakeFocus()
        let keystrokes = FakeKeystrokes()

        _ = try await makeInserter(FakePasteboard(), keystrokes, focus: focus).insert("dictated", into: Fixtures.target(nil))

        #expect(keystrokes.pastes == 1)
        #expect(focus.readCount == 1)
    }

    /// The re-read makes Accessibility calls to another app; a paste asked for on the main actor
    /// must still make them elsewhere.
    @MainActor
    @Test func readsTheFocusOffTheMainThread() async throws {
        let focus = FakeFocus()
        let keystrokes = FakeKeystrokes()

        _ = try await makeInserter(FakePasteboard(), keystrokes, focus: focus).insert("dictated", into: Fixtures.target(nil))

        #expect(keystrokes.pastes == 1)
        #expect(focus.readCount == 1)
        #expect(focus.mainThreadReadCount == 0)
    }

    /// A paste queued behind another checks the focus when its turn comes, not when it was asked.
    @Test func aQueuedPasteChecksTheFocusWhenItRuns() async throws {
        let pasteboard = FakePasteboard(items: Self.userClipboard)
        let focus = FakeFocus()
        // The first paste lands; then the user tabs into a password field.
        let keystrokes = FakeKeystrokes(onPaste: { focus.move(to: Fixtures.textEdit, secure: true) })
        let inserter = PasteboardTextInserter(pasteboard: pasteboard, keystrokes: keystrokes, focus: focus, restoreDelayMs: 30)

        /// The error a paste threw, `nil` if it pasted.
        func failure(pasting text: String) async -> InsertionError? {
            do {
                _ = try await inserter.insert(text, into: Fixtures.target(nil))
                return nil
            } catch {
                return error
            }
        }
        async let first = failure(pasting: "first")
        async let second = failure(pasting: "second")
        let failures = await [first, second]

        #expect(keystrokes.pastes == 1)
        #expect(failures.compactMap { $0 } == [.focusBecameSecure])
        #expect(pasteboard.transientWrites.count == 1)
        #expect(pasteboard.items == Self.userClipboard)
    }

    @Test func systemPasteboardUsesTheSharedMarkerNames() {
        #expect(SystemPasteboard.transientType.rawValue == "org.nspasteboard.TransientType")
        #expect(SystemPasteboard.autoGeneratedType.rawValue == "org.nspasteboard.AutoGeneratedType")
    }
}
