//! The words `WordForms` knows, as the Mac app lists them (Cleanup/WordForms.swift). Every word is
//! normalised, as `edit_distance::normalize` leaves it.

/// Words that say when: a repair may not add, drop or change one outside a correction, since "the
/// day before" is not "the day after".
pub(super) const TIME_WORDS: [&str; 50] = [
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
    "january",
    "february",
    "march",
    "april",
    "may",
    "june",
    "july",
    "august",
    "september",
    "october",
    "november",
    "december",
    "today",
    "tomorrow",
    "yesterday",
    "tonight",
    "noon",
    "midday",
    "midnight",
    "morning",
    "afternoon",
    "evening",
    "night",
    "weekend",
    "week",
    "weeks",
    "month",
    "months",
    "year",
    "years",
    "fortnight",
    "before",
    "after",
    "until",
    "till",
    "since",
    "next",
    "last",
    "ago",
    "early",
    "earlier",
    "late",
    "later",
];

/// Months a correction may swap one for another. "May" is one only when a capital or the month it
/// corrects shows it (`SelfRepair`).
pub(super) const MONTH_NAMES: [&str; 11] = [
    "january",
    "february",
    "march",
    "april",
    "june",
    "july",
    "august",
    "september",
    "october",
    "november",
    "december",
];

/// Times of day, which state when as a number does.
pub(super) const PARTS_OF_DAY: [&str; 10] = [
    "morning",
    "afternoon",
    "evening",
    "night",
    "noon",
    "midday",
    "midnight",
    "am",
    "pm",
    "o'clock",
];

/// Number words and their values.
pub(super) const UNITS: [(&str, i64); 11] = [
    ("zero", 0),
    ("oh", 0),
    ("one", 1),
    ("two", 2),
    ("three", 3),
    ("four", 4),
    ("five", 5),
    ("six", 6),
    ("seven", 7),
    ("eight", 8),
    ("nine", 9),
];

pub(super) const TEENS: [(&str, i64); 10] = [
    ("ten", 10),
    ("eleven", 11),
    ("twelve", 12),
    ("thirteen", 13),
    ("fourteen", 14),
    ("fifteen", 15),
    ("sixteen", 16),
    ("seventeen", 17),
    ("eighteen", 18),
    ("nineteen", 19),
];

pub(super) const TENS: [(&str, i64); 8] = [
    ("twenty", 20),
    ("thirty", 30),
    ("forty", 40),
    ("fifty", 50),
    ("sixty", 60),
    ("seventy", 70),
    ("eighty", 80),
    ("ninety", 90),
];

pub(super) const ORDINALS: [(&str, i64); 27] = [
    ("first", 1),
    ("second", 2),
    ("third", 3),
    ("fourth", 4),
    ("fifth", 5),
    ("sixth", 6),
    ("seventh", 7),
    ("eighth", 8),
    ("ninth", 9),
    ("tenth", 10),
    ("eleventh", 11),
    ("twelfth", 12),
    ("thirteenth", 13),
    ("fourteenth", 14),
    ("fifteenth", 15),
    ("sixteenth", 16),
    ("seventeenth", 17),
    ("eighteenth", 18),
    ("nineteenth", 19),
    ("twentieth", 20),
    ("thirtieth", 30),
    ("fortieth", 40),
    ("fiftieth", 50),
    ("sixtieth", 60),
    ("seventieth", 70),
    ("eightieth", 80),
    ("ninetieth", 90),
];

pub(super) const SCALES: [(&str, i64); 4] = [
    ("hundred", 100),
    ("thousand", 1_000),
    ("million", 1_000_000),
    ("billion", 1_000_000_000),
];

/// Number words that are not a value on their own ("half", "dozen"), which a repair keeps as said.
pub(super) const QUANTITY_WORDS: [&str; 7] = [
    "half",
    "quarter",
    "dozen",
    "point",
    "hundredth",
    "thousandth",
    "millionth",
];

/// Units written as symbols next to digits ("percent" → "%", "dollars" → "$").
pub(super) const UNIT_WORDS: [&str; 17] = [
    "percent", "degree", "degrees", "dollar", "dollars", "cent", "cents", "buck", "bucks", "pound", "pounds", "pence",
    "euro", "euros", "yen", "rupee", "rupees",
];

/// Words a grammar fix may add: articles, auxiliaries, and the prepositions and conjunctions that
/// hold a clause together ("I going" → "I am going"). No negation, no word of time.
pub(super) const INSERTABLE: [&str; 36] = [
    "a", "an", "the", "to", "of", "that", "it", "there", "and", "as", "am", "is", "are", "was", "were", "be", "been",
    "being", "have", "has", "had", "do", "does", "did", "will", "would", "for", "in", "on", "at", "with", "from",
    "about", "by", "into", "onto",
];

/// Words a grammar fix may drop without changing what was said.
pub(super) const DROPPABLE: [&str; 40] = [
    "a", "an", "the", "to", "of", "that", "it", "there", "and", "so", "just", "really", "very", "then", "well", "also",
    "quite", "pretty", "am", "is", "are", "was", "were", "be", "been", "being", "have", "has", "had", "do", "does",
    "did", "will", "for", "in", "on", "at", "with", "from", "by",
];

/// Words said to mark a list item, which a list's own numbers or bullets replace: "first",
/// "secondly", "finally", and "number" (as in "number one", whose number goes too).
pub(super) const LIST_MARKERS: [&str; 18] = [
    "first", "firstly", "second", "secondly", "third", "thirdly", "fourth", "fourthly", "fifth", "fifthly", "sixth",
    "seventh", "eighth", "ninth", "tenth", "finally", "lastly", "number",
];

/// Words a grammar or recognition fix may swap for one another: forms of the same verb or article,
/// a pronoun's case, and words speech-to-text confuses because they sound alike. Each group is its
/// words separated by spaces.
pub(super) const FORMS: [&str; 128] = [
    "am is are was were be been being",
    "have has had having",
    "do does did doing done",
    "don't doesn't didn't",
    "isn't aren't wasn't weren't ain't",
    "hasn't haven't hadn't",
    "won't wouldn't",
    "can't cannot couldn't",
    "will would",
    "can could",
    "shall should",
    "may might",
    "a an the",
    "an and",
    "this these",
    "that those",
    "i me",
    "he him",
    "she her",
    "we us",
    "they them",
    "who whom",
    "their there they're",
    "your you're",
    "its it's",
    "whose who's",
    "to too",
    "then than",
    "where were we're",
    "of have",
    "are our",
    "affect effect",
    "lose loose",
    "quite quiet",
    "advice advise",
    "breath breathe",
    "right write rite",
    "hear here",
    "meet meat",
    "sale sail",
    "weight wait",
    "week weak",
    "whole hole",
    "new knew",
    "flour flower",
    "mail male",
    "pair pear",
    "plane plain",
    "role roll",
    "sea see",
    "son sun",
    "tail tale",
    "waist waste",
    "wear where ware",
    "which witch",
    "wood would",
    "allowed aloud",
    "bare bear",
    "board bored",
    "cell sell",
    "die dye",
    "fair fare",
    "great grate",
    "heal heel",
    "hour our",
    "made maid",
    "passed past",
    "peace piece",
    "principal principle",
    "rain reign rein",
    "road rode",
    "some sum",
    "stair stare",
    "steal steel",
    "suite sweet",
    "threw through",
    "way weigh",
    "weather whether",
    "by buy bye",
    "brake break",
    "cite site sight",
    "desert dessert",
    "lead led",
    "minor miner",
    "patience patients",
    "presence presents",
    "scene seen",
    "sole soul",
    "stationary stationery",
    "tide tied",
    "vain vein",
    "dear deer",
    "find fined",
    "guessed guest",
    "hair hare",
    "higher hire",
    "horse hoarse",
    "knows nose",
    "lessen lesson",
    "missed mist",
    "pain pane",
    "peak peek",
    "pole poll",
    "pray prey",
    "real reel",
    "root route",
    "seam seem",
    "steak stake",
    "story storey",
    "team teem",
    "whirled world",
    "compliment complement",
    "council counsel",
    "capital capitol",
    "altar alter",
    "bread bred",
    "coarse course",
    "genes jeans",
    "groan grown",
    "muscle mussel",
    "naval navel",
    "profit prophet",
    "sauce source",
    "wail whale",
    "war wore",
    "weave we've",
    "read reed",
    "accept except",
];

/// Irregular verbs, each with its forms: "go", "goes", "went", "gone" are one verb. Each is its
/// forms separated by spaces.
pub(super) const IRREGULAR_VERBS: [&str; 58] = [
    "go goes went gone going",
    "get gets got gotten getting",
    "make makes made making",
    "say says said saying",
    "see sees saw seen seeing",
    "come comes came coming",
    "take takes took taken taking",
    "know knows knew known knowing",
    "think thinks thought thinking",
    "tell tells told telling",
    "give gives gave given giving",
    "find finds found finding",
    "feel feels felt feeling",
    "leave leaves left leaving",
    "bring brings brought bringing",
    "buy buys bought buying",
    "send sends sent sending",
    "pay pays paid paying",
    "meet meets met meeting",
    "run runs ran running",
    "sit sits sat sitting",
    "speak speaks spoke spoken speaking",
    "write writes wrote written writing",
    "lose loses lost losing",
    "hear hears heard hearing",
    "hold holds held holding",
    "keep keeps kept keeping",
    "begin begins began begun beginning",
    "break breaks broke broken breaking",
    "choose chooses chose chosen choosing",
    "drive drives drove driven driving",
    "fall falls fell fallen falling",
    "forget forgets forgot forgotten forgetting",
    "grow grows grew grown growing",
    "lend lends lent lending",
    "ride rides rode ridden riding",
    "ring rings rang rung ringing",
    "sell sells sold selling",
    "show shows showed shown showing",
    "sing sings sang sung singing",
    "sleep sleeps slept sleeping",
    "spend spends spent spending",
    "stand stands stood standing",
    "teach teaches taught teaching",
    "throw throws threw thrown throwing",
    "understand understands understood understanding",
    "wake wakes woke woken waking",
    "wear wears wore worn wearing",
    "catch catches caught catching",
    "build builds built building",
    "fight fights fought fighting",
    "fly flies flew flown flying",
    "draw draws drew drawn drawing",
    "become becomes became becoming",
    "seek seeks sought seeking",
    "hang hangs hung hanging",
    "sweep sweeps swept sweeping",
    "deal deals dealt dealing",
];
