import AppKit
import Shared

/// Everything that was on the pasteboard: every item, and every type's data in each item.
///
/// Taken before a paste so the user's clipboard (an image, a file, rich text with its plain-text
/// fallback) comes back exactly as it was, not just its string.
public struct PasteboardSnapshot: Sendable, Equatable {
    /// One type's data within an item, e.g. `public.utf8-plain-text` and its bytes.
    public struct Representation: Sendable, Equatable {
        public let type: String
        public let data: Data

        public init(type: String, data: Data) {
            self.type = type
            self.data = data
        }
    }

    /// One pasteboard item. Its representations keep the owner's order, which is its preference.
    public struct Item: Sendable, Equatable {
        public let representations: [Representation]

        public init(representations: [Representation]) {
            self.representations = representations
        }
    }

    public let items: [Item]

    public init(items: [Item]) {
        self.items = items
    }

    public var isEmpty: Bool { items.isEmpty }
}

/// The general pasteboard, behind a protocol so paste and restore are tested without touching the
/// user's clipboard.
public protocol PasteboardAccess: Sendable {
    /// Increases whenever anyone writes to the pasteboard; used to tell whether the user copied
    /// something while a paste was in flight.
    var changeCount: Int { get }
    /// Captures every item and every type's data.
    func snapshot() -> PasteboardSnapshot
    /// Replaces the pasteboard's contents with `snapshot` (an empty snapshot clears it).
    @discardableResult
    func restore(_ snapshot: PasteboardSnapshot) -> Bool
    /// Writes `text` for a paste, marked transient and auto-generated so clipboard managers do not
    /// record it (see nspasteboard.org).
    /// - Returns: The change count right after the write, or `nil` if the pasteboard refused it.
    func writeTransient(_ text: String) -> Int?
    /// Writes `text` as an ordinary copy, for the user to paste themselves (no transient markers,
    /// so clipboard managers do keep it).
    /// - Returns: Whether the pasteboard accepted it.
    func writeString(_ text: String) -> Bool
}

/// ``PasteboardAccess`` over `NSPasteboard.general`.
///
/// Holds no reference to the pasteboard, so it is trivially `Sendable`. `NSPasteboard` is not
/// declared main-actor-only; each method here is one complete read or write of the pasteboard
/// server, and the paste inserter never runs two of them at once.
public struct SystemPasteboard: PasteboardAccess {
    /// Marks a pasteboard write that clipboard managers should not record.
    public static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    /// Marks a pasteboard write that software made rather than the user.
    public static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    public init() {}

    private var pasteboard: NSPasteboard { .general }

    public var changeCount: Int { pasteboard.changeCount }

    public func snapshot() -> PasteboardSnapshot {
        // Reading each type forces any promised (lazily provided) data now, while the owner is
        // still around to provide it.
        let items = (pasteboard.pasteboardItems ?? []).map { item in
            PasteboardSnapshot.Item(representations: item.types.compactMap { type in
                item.data(forType: type).map { PasteboardSnapshot.Representation(type: type.rawValue, data: $0) }
            })
        }
        return PasteboardSnapshot(items: items.filter { !$0.representations.isEmpty })
    }

    @discardableResult
    public func restore(_ snapshot: PasteboardSnapshot) -> Bool {
        pasteboard.clearContents()
        guard !snapshot.isEmpty else { return true }
        let items = snapshot.items.map { snapshotItem in
            let item = NSPasteboardItem()
            for representation in snapshotItem.representations {
                item.setData(representation.data, forType: NSPasteboard.PasteboardType(representation.type))
            }
            return item
        }
        let restored = pasteboard.writeObjects(items)
        if !restored {
            Log.insertion.error("The clipboard could not be restored after pasting (\(items.count, privacy: .public) items)")
        }
        return restored
    }

    public func writeTransient(_ text: String) -> Int? {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        let written = item.setString(text, forType: .string)
            && item.setData(Data(), forType: Self.transientType)
            && item.setData(Data(), forType: Self.autoGeneratedType)
        guard written, pasteboard.writeObjects([item]) else {
            Log.insertion.error("The dictated text could not be put on the pasteboard for pasting")
            return nil
        }
        return pasteboard.changeCount
    }

    public func writeString(_ text: String) -> Bool {
        pasteboard.clearContents()
        let written = pasteboard.setString(text, forType: .string)
        if !written {
            Log.insertion.error("The dictated text could not be copied to the clipboard")
        }
        return written
    }
}
